import { loadRuntimeSceneManifest } from "../../engine/data/index.js";
import {
	mirandaDeckAssetManifest,
	observatoryAssetManifest,
	portalArenaAssetManifest,
	prototypeAssetManifest,
} from "../assets/index.js";
import {
	mirandaDeckPrefabs,
	observatoryPrefabs,
	portalArenaPrefabs,
	prototypePrefabs,
} from "../prefabs/index.js";
import { mirandaDeckLevel, prototypeLevel } from "./defaultLevels.js";
import { observatoryLevel } from "./observatoryLevel.js";
import { portalArenaLevel } from "./portalArenaLevel.js";
import {
	mirandaDeckRenderProfile,
	observatoryRenderProfile,
	portalArenaRenderProfile,
	prototypeRenderProfile,
} from "./renderProfiles.js";

export const portalArenaRuntimeSceneManifest = loadRuntimeSceneManifest({
	schemaVersion: 1,
	id: "portal_arena_runtime",
	generatedAt: "2026-06-05T00:00:00.000Z",
	source: {
		kind: "authored",
		id: "portal_arena",
	},
	level: portalArenaLevel,
	prefabs: portalArenaPrefabs,
	assets: portalArenaAssetManifest,
	renderProfile: portalArenaRenderProfile,
	readiness: {
		playerStableId: "player",
		requiredAssetIds: [
			"mesh_player",
			"mesh_portal_field",
			"mesh_portal_gate",
			"cubemap_classic_sky",
			"material_player",
			"audio_player_jump",
			"audio_player_charge_release",
			"audio_portal_activate",
			"audio_ambient_portal_deck",
			"audio_ambient_shadow_waltz",
			"audio_ambient_whistling_dreams",
		],
		requiredCollisionPrefabIds: ["portal_arena_floor", "portal_gate", "player"],
		requiredCollisionStableIds: [
			"portal-arena:floor",
			"portal-arena:portal:prototype-arena",
			"portal-arena:portal:miranda-deck",
			"portal-arena:portal:observatory",
			"player",
		],
		requiredLightStableIds: ["player"],
	},
});

export const prototypeRuntimeSceneManifest = loadRuntimeSceneManifest({
	schemaVersion: 1,
	id: "prototype_arena_runtime",
	generatedAt: "2026-06-05T00:00:00.000Z",
	source: {
		kind: "prototype",
		id: "prototype_arena",
	},
	level: prototypeLevel,
	prefabs: prototypePrefabs,
	assets: prototypeAssetManifest,
	renderProfile: prototypeRenderProfile,
	readiness: {
		playerStableId: "player",
		requiredAssetIds: [
			"mesh_player",
			"mesh_arena_floor",
			"mesh_ingredient",
			"cubemap_classic_sky",
			"material_player",
			"material_arena_floor",
			"material_ingredient",
			"audio_ui_collect",
			"audio_player_jump",
			"audio_player_charge_release",
		],
		requiredCollisionPrefabIds: ["arena_floor", "player"],
	},
});

export const mirandaDeckRuntimeSceneManifest = loadRuntimeSceneManifest({
	schemaVersion: 1,
	id: "miranda_deck_runtime",
	generatedAt: "2026-06-05T00:00:00.000Z",
	source: {
		kind: "authored",
		id: "miranda.scene#deck",
	},
	level: mirandaDeckLevel,
	prefabs: mirandaDeckPrefabs,
	assets: mirandaDeckAssetManifest,
	renderProfile: mirandaDeckRenderProfile,
	readiness: {
		playerStableId: "player",
		requiredAssetIds: [
			"mesh_player",
			"mesh_box",
			"mesh_cylinder",
			"mesh_miranda_engine_core",
			"cubemap_observatory_sky",
			"material_player",
			"material_miranda_floor_main",
			"material_miranda_floor_upper",
			"material_miranda_cockpit_panel",
			"material_miranda_cockpit_panel_center",
			"material_miranda_crew_bunk",
			"material_miranda_locker_bank",
			"material_miranda_captains_desk",
			"material_miranda_captains_chair",
			"material_miranda_recipe_safe",
			"material_miranda_engine_column",
			"material_miranda_engine_core",
			"material_miranda_med_pod",
			"material_miranda_mess_table",
			"material_miranda_mess_counter",
			"material_miranda_chapel_altar",
			"material_miranda_brig_cell",
			"material_miranda_brig_desk",
			"material_miranda_cargo_stack_a",
			"material_miranda_cargo_stack",
			"material_miranda_server_bank",
			"material_miranda_server_bank_wide",
			"material_miranda_story_marker_cyan",
			"material_miranda_story_marker_amber",
			"material_miranda_story_marker_red",
			"material_miranda_story_marker_magenta",
			"audio_player_jump",
			"audio_player_charge_release",
			"audio_ambient_wicked_shadows_whisper",
			"audio_ambient_dark_shadows_of_delight",
			"audio_ambient_shadow_waltz",
		],
		requiredCollisionPrefabIds: [
			"miranda_floor_main",
			"miranda_floor_upper",
			"miranda_cockpit_panel_side",
			"miranda_cockpit_panel_center",
			"miranda_crew_bunk",
			"miranda_locker_bank",
			"miranda_captains_desk",
			"miranda_captains_chair",
			"miranda_recipe_safe",
			"miranda_engine_column",
			"miranda_engine_core",
			"miranda_med_pod",
			"miranda_mess_table_large",
			"miranda_mess_table_small",
			"miranda_mess_counter",
			"miranda_chapel_altar",
			"miranda_brig_cell",
			"miranda_brig_desk",
			"miranda_cargo_stack_a",
			"miranda_cargo_stack_b",
			"miranda_cargo_stack_c",
			"miranda_cargo_stack_d",
			"miranda_server_bank_tall",
			"miranda_server_bank_wide",
			"miranda_story_marker_cyan",
			"miranda_story_marker_amber",
			"miranda_story_marker_red",
			"miranda_story_marker_magenta",
			"player",
		],
		requiredCollisionStableIds: [
			"miranda:floor:main",
			"miranda:floor:upper",
			"miranda:cockpit:panel:left",
			"miranda:cockpit:panel:center",
			"miranda:cockpit:panel:right",
			"miranda:crew:bunk:port:a",
			"miranda:crew:bunk:port:b",
			"miranda:crew:bunk:starboard:a",
			"miranda:crew:bunk:starboard:b",
			"miranda:crew:locker-bank",
			"miranda:captain:desk",
			"miranda:captain:chair",
			"miranda:captain:recipe-safe",
			"miranda:engine:core",
			"miranda:engine:column:a",
			"miranda:engine:column:b",
			"miranda:engine:column:c",
			"miranda:engine:column:d",
			"miranda:medbay:pod:a",
			"miranda:medbay:pod:b",
			"miranda:medbay:pod:c",
			"miranda:medbay:pod:d",
			"miranda:mess:table:a",
			"miranda:mess:table:b",
			"miranda:mess:counter",
			"miranda:chapel:altar",
			"miranda:brig:cell:a",
			"miranda:brig:cell:b",
			"miranda:brig:cell:c",
			"miranda:brig:cell:d",
			"miranda:brig:desk",
			"miranda:cargo:stack:a",
			"miranda:cargo:stack:b",
			"miranda:cargo:stack:c",
			"miranda:cargo:stack:d",
			"miranda:archive:server-bank:a",
			"miranda:archive:server-bank:b",
			"miranda:archive:server-bank:c",
			"miranda:archive:server-bank:d",
			"miranda:archive:server-bank:e",
			"miranda:cockpit:story-note:captain-log",
			"miranda:crew:story-note:medical-watch",
			"miranda:captain:story-note:first-officer",
			"miranda:captain:story-note:vault-fragment",
			"miranda:engine:story-note:engineering-memo",
			"miranda:medbay:story-note:quarantine",
			"miranda:mess:story-note:ledger",
			"miranda:brig:story-note:confession",
			"miranda:archive:story-note:index",
			"player",
		],
		requiredLightStableIds: [
			"miranda:command-gallery:beacon-light",
			"miranda:observation-gallery:light",
			"miranda:archive-gallery:light",
		],
	},
});

export const observatoryRuntimeSceneManifest = loadRuntimeSceneManifest({
	schemaVersion: 1,
	id: "observatory_runtime",
	generatedAt: "2026-06-06T00:00:00.000Z",
	source: {
		kind: "authored",
		id: "observatory.scene#playable-foundation",
	},
	level: observatoryLevel,
	prefabs: observatoryPrefabs,
	assets: observatoryAssetManifest,
	renderProfile: observatoryRenderProfile,
	readiness: {
		playerStableId: "player",
		requiredAssetIds: [
			"mesh_player",
			"mesh_observatory_environment",
			"mesh_water_plane",
			"mesh_observatory_firefly_marker",
			"cubemap_observatory_sky",
			"material_player",
			"material_water_dark_still",
			"material_observatory_firefly",
			"audio_player_jump",
			"audio_player_charge_release",
		],
		requiredCollisionPrefabIds: ["observatory_walkable_proxy", "player"],
		requiredCollisionStableIds: ["observatory:walkable-proxy", "player"],
		requiredLightStableIds: [
			"player",
			"observatory:firefly:archive",
			"observatory:firefly:lantern",
			"observatory:firefly:tide",
		],
	},
});

export const defaultRuntimeSceneManifests = [
	portalArenaRuntimeSceneManifest,
	prototypeRuntimeSceneManifest,
	mirandaDeckRuntimeSceneManifest,
	observatoryRuntimeSceneManifest,
] as const;

export const defaultRuntimeSceneManifest = portalArenaRuntimeSceneManifest;

export function getRuntimeSceneManifest(
	id: string,
): (typeof defaultRuntimeSceneManifests)[number] | undefined {
	return defaultRuntimeSceneManifests.find((manifest) => manifest.id === id);
}
