export const CANONICAL_CONVERSATION_PROFILE_IDS = Object.freeze([
  'ava-chen',
  'eleanor-kim',
  'elara-voss',
  'gregory-aster',
  'helena-zhao',
  'kaelen-vance',
  'maya-okafor',
  'merkin',
  'soren-klein',
  'vex-kanarath',
])

export const CONVERSATION_PROFILE_ALIAS_ENTRIES = Object.freeze([
  ['ava', 'ava-chen'],
  ['firefly_ava', 'ava-chen'],
  ['eleanor', 'eleanor-kim'],
  ['firefly_eleanor', 'eleanor-kim'],
  ['elara', 'elara-voss'],
  ['firefly_elara', 'elara-voss'],
  ['firefly_elara_elara', 'elara-voss'],
  ['gregory', 'gregory-aster'],
  ['firefly_gregory', 'gregory-aster'],
  ['helena', 'helena-zhao'],
  ['firefly_helena', 'helena-zhao'],
  ['firefly_helena_helena', 'helena-zhao'],
  ['kaelen', 'kaelen-vance'],
  ['firefly_kaelen', 'kaelen-vance'],
  ['maya', 'maya-okafor'],
  ['firefly_maya', 'maya-okafor'],
  ['merkin', 'merkin'],
  ['firefly_merkin', 'merkin'],
  ['soren', 'soren-klein'],
  ['firefly_soren', 'soren-klein'],
  ['vex', 'vex-kanarath'],
  ['firefly_vex', 'vex-kanarath'],
])
