import type { EditorSceneDocument, EditorSceneNode } from './editorTypes'
import mirandaPackagedScene from './scenes/miranda.scene.json'
import observatoryPackagedScene from './scenes/observatory.scene.json'
import sciFiRoomPackagedScene from './scenes/sci-fi-room.scene.json'
import solitudePackagedScene from './scenes/solitude.scene.json'
import yggdrasilPackagedScene from './scenes/yggdrasil.scene.json'

function nowIso() {
  return new Date().toISOString()
}

const SCI_FI_ROOM_SCENE_VERSION = 5
const SCI_FI_FLOOR_ROOT_ID = 'sci-fi-floor-root'
const SCI_FI_PLANTER_B_ASSET_URL =
  '/generated/hunyuan3d/growth-planter-b-generated-2026-04-18t01-36-15-986z/growth-planter-b-generated-2026-04-18t01-36-15-986z-texture-wrap-2026-04-18T01-38-19-536Z.glb'
const SCI_FI_ROOM_SCALE = 4
const SCI_FI_ROOM_WIDTH = 5.39 * SCI_FI_ROOM_SCALE
const SCI_FI_ROOM_DEPTH = 4.63 * SCI_FI_ROOM_SCALE
const SCI_FI_ROOM_FLOOR_Y = -0.08 * SCI_FI_ROOM_SCALE
const SCI_FI_ROOM_WALL_THICKNESS = 0.12 * SCI_FI_ROOM_SCALE
const SCI_FI_ROOM_COURTYARD_Z = SCI_FI_ROOM_DEPTH + 3.0
const SCI_FI_ROOM_WASTELAND_Z = SCI_FI_ROOM_DEPTH + 6.0
const SCI_FI_ROOM_WASTELAND_TILE_THICKNESS = SCI_FI_ROOM_WALL_THICKNESS * 0.8
const PACKAGED_DEFAULT_SCENES: Record<string, EditorSceneDocument> = {
  observatory: observatoryPackagedScene as EditorSceneDocument,
  'sci-fi-room': sciFiRoomPackagedScene as EditorSceneDocument,
  miranda: mirandaPackagedScene as EditorSceneDocument,
  solitude: solitudePackagedScene as EditorSceneDocument,
  yggdrasil: yggdrasilPackagedScene as unknown as EditorSceneDocument,
}

function getPackagedDefaultScene(levelId: string) {
  const scene = PACKAGED_DEFAULT_SCENES[levelId]
  return scene ? (structuredClone(scene) as EditorSceneDocument) : null
}

function createSolitudeGroundNodes(): EditorSceneNode[] {
  return [
    {
      id: 'solitude-ground-root',
      name: 'Solitude Ground',
      kind: 'group',
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
    },
    {
      id: 'solitude-ground-plateau',
      name: 'Solitude Plateau',
      kind: 'primitive',
      parentId: 'solitude-ground-root',
      position: [0, -1.2, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      collision: { shape: 'cuboid', friction: 0.92 },
      primitive: {
        geometry: 'box',
        args: [240, 2.4, 240],
        color: '#6b7480',
        emissive: '#242d38',
        emissiveIntensity: 0.05,
        metalness: 0.06,
        roughness: 0.94,
      },
    },
    {
      id: 'solitude-ground-dais',
      name: 'Ruin Dais',
      kind: 'primitive',
      parentId: 'solitude-ground-root',
      position: [0, -0.18, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      collision: { shape: 'cuboid', friction: 0.94 },
      primitive: {
        geometry: 'box',
        args: [44, 0.8, 44],
        color: '#7b8797',
        emissive: '#2f3947',
        emissiveIntensity: 0.08,
        metalness: 0.08,
        roughness: 0.9,
      },
    },
  ]
}

function createMirandaGroundNodes(): EditorSceneNode[] {
  return [
    {
      id: 'miranda-ground-root',
      name: 'Miranda Structure Shell',
      kind: 'group',
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
    },
    {
      id: 'miranda-floor-main',
      name: 'Main Deck Floor',
      kind: 'primitive',
      parentId: 'miranda-ground-root',
      position: [0, 3.35, -4],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      collision: { shape: 'cuboid', friction: 0.88 },
      primitive: {
        geometry: 'box',
        args: [40, 1.2, 92],
        color: '#252d37',
        emissive: '#10161d',
        emissiveIntensity: 0.05,
        metalness: 0.72,
        roughness: 0.4,
      },
    },
    {
      id: 'miranda-floor-upper',
      name: 'Upper Deck Plate',
      kind: 'primitive',
      parentId: 'miranda-ground-root',
      position: [0, 4.7, -27.5],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      collision: { shape: 'cuboid', friction: 0.88 },
      primitive: {
        geometry: 'box',
        args: [18, 0.9, 18],
        color: '#2e3844',
        emissive: '#141b23',
        emissiveIntensity: 0.04,
        metalness: 0.76,
        roughness: 0.36,
      },
    },
  ]
}

function createObservatoryGroundNodes(): EditorSceneNode[] {
  return [
    {
      id: 'observatory-ground-root',
      name: 'Observatory Grounds',
      kind: 'group',
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
    },
    {
      id: 'observatory-ground-meadow',
      name: 'Observatory Meadow',
      kind: 'primitive',
      parentId: 'observatory-ground-root',
      position: [-137.2, 18.8, -49.5],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      collision: { shape: 'cuboid', friction: 0.96 },
      primitive: {
        geometry: 'box',
        args: [260, 2.4, 260],
        color: '#6f8e63',
        emissive: '#223224',
        emissiveIntensity: 0.04,
        metalness: 0.04,
        roughness: 0.96,
      },
    },
    {
      id: 'observatory-arrival-plaza',
      name: 'Arrival Plaza',
      kind: 'primitive',
      parentId: 'observatory-ground-root',
      position: [-137.2, 20.1, -43.5],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      collision: { shape: 'cuboid', friction: 0.92 },
      primitive: {
        geometry: 'box',
        args: [28, 0.9, 34],
        color: '#9ca87f',
        emissive: '#344028',
        emissiveIntensity: 0.06,
        metalness: 0.08,
        roughness: 0.88,
      },
    },
  ]
}

function createSciFiRoomFloorNodes(): EditorSceneNode[] {
  const floorNodes: EditorSceneNode[] = [
    {
      id: SCI_FI_FLOOR_ROOT_ID,
      name: 'Floor Root',
      kind: 'group',
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
    },
    {
      id: 'sci-fi-floor-interior-group',
      name: 'Interior Floor',
      kind: 'group',
      parentId: SCI_FI_FLOOR_ROOT_ID,
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
    },
    {
      id: 'sci-fi-floor-interior-slab',
      name: 'Interior Floor Slab',
      kind: 'primitive',
      parentId: 'sci-fi-floor-interior-group',
      position: [0, SCI_FI_ROOM_FLOOR_Y - SCI_FI_ROOM_WALL_THICKNESS / 2, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      collision: { shape: 'cuboid', friction: 0.9 },
      primitive: {
        geometry: 'box',
        args: [
          SCI_FI_ROOM_WIDTH,
          SCI_FI_ROOM_WALL_THICKNESS,
          SCI_FI_ROOM_DEPTH,
        ],
        color: '#1a2630',
        emissive: '#1a3d4a',
        emissiveIntensity: 0.45,
        metalness: 0.82,
        roughness: 0.34,
      },
    },
    {
      id: 'sci-fi-floor-courtyard-group',
      name: 'Courtyard Floor',
      kind: 'group',
      parentId: SCI_FI_FLOOR_ROOT_ID,
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
    },
    {
      id: 'sci-fi-floor-courtyard-slab',
      name: 'Courtyard Floor Slab',
      kind: 'primitive',
      parentId: 'sci-fi-floor-courtyard-group',
      position: [
        0,
        SCI_FI_ROOM_FLOOR_Y - SCI_FI_ROOM_WALL_THICKNESS / 2,
        SCI_FI_ROOM_COURTYARD_Z,
      ],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      collision: { shape: 'cuboid', friction: 0.7 },
      primitive: {
        geometry: 'box',
        args: [
          SCI_FI_ROOM_WIDTH * 1.2,
          SCI_FI_ROOM_WALL_THICKNESS,
          SCI_FI_ROOM_WIDTH * 1.2,
        ],
        color: '#1a2d3a',
        metalness: 0.42,
        roughness: 0.54,
      },
    },
    {
      id: 'sci-fi-floor-wasteland-group',
      name: 'Wasteland Floor',
      kind: 'group',
      parentId: SCI_FI_FLOOR_ROOT_ID,
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
    },
  ]

  for (let i = 0; i < 6; i += 1) {
    for (let j = 0; j < 6; j += 1) {
      const x = (i - 2.5) * (SCI_FI_ROOM_WIDTH * 2.0)
      const z = (j - 2.5) * (SCI_FI_ROOM_WIDTH * 2.0) + SCI_FI_ROOM_WASTELAND_Z
      const y =
        SCI_FI_ROOM_FLOOR_Y + Math.sin(i * 0.7) * 0.8 + Math.cos(j * 0.7) * 0.8

      floorNodes.push({
        id: `sci-fi-floor-wasteland-tile-${i}-${j}`,
        name: `Wasteland Tile ${i + 1}-${j + 1}`,
        kind: 'primitive',
        parentId: 'sci-fi-floor-wasteland-group',
        position: [x, y, z],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        visible: true,
        collision: { shape: 'cuboid', friction: 0.5 },
        primitive: {
          geometry: 'box',
          args: [
            SCI_FI_ROOM_WIDTH,
            SCI_FI_ROOM_WASTELAND_TILE_THICKNESS,
            SCI_FI_ROOM_WIDTH,
          ],
          color: '#3a3a2a',
          metalness: 0.12,
          roughness: 0.92,
        },
      })
    }
  }

  return floorNodes
}

function normalizeSciFiPlanterB(
  scene: EditorSceneDocument,
): EditorSceneDocument {
  const planterIndex = scene.nodes.findIndex(
    node => node.id === 'sci-fi-planter-b',
  )
  if (planterIndex === -1) return scene

  const planter = scene.nodes[planterIndex]
  const nextPlanter: EditorSceneNode = {
    ...planter,
    kind: 'asset',
    position: [3.0, 0, 25.52],
    rotation: [0, 0.6, 0],
    scale: [1, 1, 1],
    visible: true,
    asset: { url: SCI_FI_PLANTER_B_ASSET_URL },
  }

  nextPlanter.prefab = undefined

  const nextNodes = [...scene.nodes]
  nextNodes[planterIndex] = nextPlanter

  return {
    ...scene,
    nodes: nextNodes,
  }
}

export function upgradeLegacySceneDocument(
  scene: EditorSceneDocument,
): EditorSceneDocument {
  const normalizedScene =
    scene.levelId === 'sci-fi-room' ? normalizeSciFiPlanterB(scene) : scene

  const defaultScene = createDefaultSceneForLevel(normalizedScene.levelId)
  const nextVersion =
    normalizedScene.levelId === 'sci-fi-room'
      ? Math.max(normalizedScene.version, SCI_FI_ROOM_SCENE_VERSION)
      : normalizedScene.version

  if (!defaultScene.nodes.length) {
    return {
      ...normalizedScene,
      version: nextVersion,
    }
  }

  const existingIds = new Set(normalizedScene.nodes.map(node => node.id))
  const missingDefaultNodes = defaultScene.nodes.filter(
    node => !existingIds.has(node.id),
  )

  if (missingDefaultNodes.length === 0) {
    return {
      ...normalizedScene,
      version: nextVersion,
    }
  }

  const defaultNodeCount = defaultScene.nodes.length
  const currentNodeCount = normalizedScene.nodes.length
  const missingRatio =
    missingDefaultNodes.length / Math.max(defaultNodeCount, 1)
  const shouldRepairFromDefaults =
    currentNodeCount === 0 ||
    currentNodeCount < defaultNodeCount * 0.75 ||
    missingRatio > 0.2

  if (!shouldRepairFromDefaults) {
    return {
      ...normalizedScene,
      version: nextVersion,
    }
  }

  return {
    ...normalizedScene,
    version: nextVersion,
    nodes: [...normalizedScene.nodes, ...missingDefaultNodes],
  }
}

function createSolitudeNodes(): EditorSceneNode[] {
  const ringRadius = 18
  const pillarCount = 12
  const pillarNodes: EditorSceneNode[] = Array.from(
    { length: pillarCount },
    (_, index) => {
      const angle = (index / pillarCount) * Math.PI * 2
      const pillarHeight = index % 3 === 0 ? 5.4 : index % 2 === 0 ? 4.7 : 4.1
      const scaleX = 1.15 + (index % 4) * 0.08
      const scaleZ = 0.96 + (index % 3) * 0.06

      return {
        id: `solitude-pillar-${index + 1}`,
        name: `Solitude Pillar ${index + 1}`,
        kind: 'prefab',
        parentId: 'solitude-ruin-ring',
        position: [
          Math.cos(angle) * ringRadius,
          pillarHeight / 2,
          Math.sin(angle) * ringRadius,
        ],
        rotation: [0, angle + (index % 2 === 0 ? 0.12 : -0.16), 0],
        scale: [scaleX, pillarHeight, scaleZ],
        visible: true,
        prefab: { type: 'wasteland-monolith' },
      }
    },
  )
  const pillarFireflyNodes: EditorSceneNode[] = pillarNodes.map(
    (pillarNode, index) => ({
      id: `solitude-pillar-firefly-${index + 1}`,
      name: `${pillarNode.name} Firefly`,
      kind: 'group',
      parentId: 'solitude-ruin-ring',
      position: [
        pillarNode.position[0],
        pillarNode.scale[1] + 0.8,
        pillarNode.position[2],
      ],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      gameplay: {
        type: 'firefly',
        markerColor: '#f5f1a8',
        markerSize: 0.52,
        lightBurstBoost: 1.4,
        title: pillarNode.name,
        author: 'Pillar Firefly',
        location: 'The Solitude Plain',
        excerpt: `A patient glow hovers above ${pillarNode.name}.`,
        body: `A solitary firefly keeps watch above ${pillarNode.name}.`,
      },
    }),
  )

  return [
    {
      id: 'solitude-ruin-ring',
      name: 'Ruin Ring',
      kind: 'group',
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
    },
    ...pillarNodes,
    ...pillarFireflyNodes,
    {
      id: 'solitude-ring-fragment-east',
      name: 'Ring Fragment East',
      kind: 'prefab',
      parentId: 'solitude-ruin-ring',
      position: [11.5, 0.28, 0.8],
      rotation: [0, 0.62, 0],
      scale: [1, 1, 1],
      visible: true,
      prefab: { type: 'broken-ring' },
    },
    {
      id: 'solitude-ring-fragment-west',
      name: 'Ring Fragment West',
      kind: 'prefab',
      parentId: 'solitude-ruin-ring',
      position: [-10.8, 0.2, -1.4],
      rotation: [0, -1.04, 0],
      scale: [0.84, 0.84, 0.84],
      visible: true,
      prefab: { type: 'broken-ring' },
    },
    {
      id: 'solitude-firefly',
      name: 'Firefly of Solitude',
      kind: 'group',
      position: [0, 2.6, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      gameplay: {
        type: 'firefly',
        markerColor: '#f5f1a8',
        markerSize: 0.62,
        lightBurstBoost: 1.75,
        title: 'Solitude',
        author: 'The Firefly',
        location: 'The Solitude Plain',
        excerpt:
          'A single patient glow waits at the center of the ruined ring.',
        body: 'This is a place for solitude. You are alone here.\n\nThe pillars keep their distance so the sky can speak without interruption.',
      },
    },
    {
      id: 'solitude-ambient-wind',
      name: 'Solitude Wind Region',
      kind: 'group',
      position: [0, 4, 0],
      rotation: [0, 0, 0],
      scale: [120, 18, 120],
      visible: true,
      gameplay: {
        type: 'audio-region',
        markerColor: '#7ecbff',
        title: 'Plain Wind',
        audioTrack: '/audio/ambient/Wicked Shadows Whisper.mp3',
        audioVolume: 0.28,
        regionFalloff: 24,
      },
    },
    {
      id: 'solitude-ring-haze',
      name: 'Ring Haze Volume',
      kind: 'group',
      position: [0, 4, 0],
      rotation: [0, 0, 0],
      scale: [52, 12, 52],
      visible: true,
      gameplay: {
        type: 'fog-volume',
        markerColor: '#d7e2f6',
        title: 'Ruin Haze',
        fogColor: '#8f9daf',
        fogDensity: 0.0026,
        regionFalloff: 10,
      },
    },
  ]
}

export function createDefaultSceneForLevel(
  levelId: string,
): EditorSceneDocument {
  const packagedScene = getPackagedDefaultScene(levelId)
  if (packagedScene) {
    return packagedScene
  }

  if (levelId === 'solitude') {
    return {
      levelId,
      version: 1,
      updatedAt: nowIso(),
      settings: {
        level: {
          presets: {
            atmosphere: 'lonely-wind',
            audio: 'lonely-wind',
          },
          spawn: {
            position: [0, 2.4, -24],
          },
          features: {
            starMap: true,
            conversations: true,
            water: false,
            styles: true,
            ambientParticles: true,
          },
          style: {
            preset: 'monument',
            enabled: true,
            fog: {
              color: '#7b8797',
              density: 0.00045,
            },
          },
          lighting: {
            ambientIntensity: 0.75,
            keyLightIntensity: 0.7,
            fillLightIntensity: 0.22,
          },
          water: {
            enabled: false,
            level: -0.16,
            size: {
              width: 800,
              height: 800,
            },
            color: '#425d72',
            opacity: 0.86,
            enableAnimation: true,
          },
          ambientParticles: {
            enabled: true,
            count: 180,
            radius: 140,
            minHeight: 0.8,
            maxHeight: 18,
            color: '#b8d9ff',
            secondaryColor: '#f3e8b2',
            size: 1.15,
            opacity: 0.26,
            driftSpeed: 0.22,
            sway: 0.85,
          },
        },
        solitude: {
          skyboxPreset: 'observatory',
        },
      },
      nodes: [...createSolitudeGroundNodes(), ...createSolitudeNodes()],
    }
  }

  if (levelId === 'sci-fi-room') {
    return {
      levelId,
      version: SCI_FI_ROOM_SCENE_VERSION,
      updatedAt: nowIso(),
      settings: {
        level: {
          spawn: {
            position: [-137.2, 20, -49.5],
          },
          skyboxPreset: 'observatory',
          features: {
            ocean: true,
            vegetation: true,
            fireflies: true,
            starMap: true,
            conversations: true,
            styles: true,
          },
          style: {
            preset: 'ghibli',
            enabled: true,
            fog: {
              color: '#87CEEB',
              density: 0.002,
            },
            colorGrading: {
              saturation: 1.2,
              contrast: 1.1,
              brightness: 1,
              warmth: 1.05,
            },
            bloom: {
              intensity: 0.3,
              threshold: 0.9,
            },
          },
          lighting: {
            ambientIntensity: 10.4,
            sunIntensity: 0.8,
            fillIntensity: 0.3,
            fallbackAmbientIntensity: 4.8,
            fallbackMoonlightIntensity: 0.45,
            fallbackFillLightIntensity: 0.2,
          },
        },
        observatory: {
          ocean: {
            size: {
              width: 4000,
              height: 4000,
            },
            enableRising: true,
            initialLevel: -2,
            targetLevel: 5,
            riseRate: 0.01,
            enableAnimation: true,
            underwaterFogDensity: 0.1,
            underwaterFogColor: 533536,
            surfaceFogDensity: 0.001,
          },
        },
      },
      nodes: [
        ...createSciFiRoomFloorNodes(),
        {
          id: 'sci-fi-anomaly-a',
          name: 'Anomaly Cluster A',
          kind: 'prefab',
          position: [-2.5, 1.48, 2.0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'anomaly-cluster', variant: 'magenta' },
        },
        {
          id: 'sci-fi-anomaly-b',
          name: 'Anomaly Cluster B',
          kind: 'prefab',
          position: [2.8, 1.18, 1.5],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'anomaly-cluster', variant: 'green' },
        },
        {
          id: 'sci-fi-anomaly-c',
          name: 'Anomaly Cluster C',
          kind: 'prefab',
          position: [-4.2, 1.98, 2.8],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'anomaly-cluster', variant: 'cyan' },
        },
        {
          id: 'sci-fi-anomaly-d',
          name: 'Anomaly Cluster D',
          kind: 'prefab',
          position: [4.6, 1.28, 2.1],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'anomaly-cluster', variant: 'rose' },
        },
        {
          id: 'sci-fi-console',
          name: 'Command Console',
          kind: 'prefab',
          position: [0, 0, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'command-console' },
        },
        {
          id: 'sci-fi-portal',
          name: 'Observatory Portal',
          kind: 'prefab',
          position: [-9.98, -0.32, -8.26],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'portal-apparatus' },
          gameplay: {
            type: 'portal',
            targetLevelId: 'observatory',
            markerColor: '#ff8cff',
            markerSize: 1.1,
          },
        },
        {
          id: 'sci-fi-story-pillar',
          name: 'Story Marker · Pillar',
          kind: 'prefab',
          position: [3.0, 1.18, -2.0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'story-marker', variant: 'magenta' },
          gameplay: {
            type: 'note',
            markerColor: '#ff00ff',
            markerSize: 0.62,
            title: 'Pillar Whisper',
            author: 'Architectural Residue',
            location: 'Command Center',
            excerpt:
              'The pillar hums first, like a machine trying to remember the language of prayer.',
            body: 'The pillar hums first, like a machine trying to remember the language of prayer.\n\nIts glow is not decorative. It pulses in measured intervals, as if syncing itself to some vanished crew protocol.\n\nEven here, the room seems to prefer ritual to utility.',
          },
        },
        {
          id: 'sci-fi-story-bench',
          name: 'Story Marker · Bench',
          kind: 'prefab',
          position: [0, 0.38, 19.52],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'story-marker', variant: 'amber' },
          gameplay: {
            type: 'note',
            markerColor: '#ffaa00',
            markerSize: 0.58,
            title: 'Bench Note',
            author: 'Unknown Visitor',
            location: 'Courtyard Threshold',
            excerpt:
              'The bench offers a pause before the open sky, its carved warning almost tender: look up before you go farther.',
            body: 'The bench offers a pause before the open sky, its carved warning almost tender: look up before you go farther.\n\nWhatever was built here expected hesitation.\n\nIt wanted people to stop, adjust to the stars, and only then continue.',
          },
        },
        {
          id: 'sci-fi-story-fountain',
          name: 'Story Marker · Fountain',
          kind: 'prefab',
          position: [0, 0.6, 21.52],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'story-marker', variant: 'cyan' },
          gameplay: {
            type: 'note',
            markerColor: '#00ccff',
            markerSize: 0.64,
            title: 'Fountain Inscription',
            author: 'Central Basin Archive',
            location: 'Courtyard Core',
            excerpt:
              'At the courtyard heart, the fountain mirrors the constellations, as if the room is learning to become an observatory.',
            body: 'At the courtyard heart, the fountain mirrors the constellations, as if the room is learning to become an observatory.\n\nThe basin does not reflect what is above so much as rehearse it.\n\nThis place is less a room than a machine for becoming sky-aware.',
          },
        },
        {
          id: 'sci-fi-story-plant',
          name: 'Story Marker · Plant',
          kind: 'prefab',
          position: [3.0, 1.88, 25.52],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'story-marker', variant: 'green' },
          gameplay: {
            type: 'note',
            markerColor: '#5edeb9',
            markerSize: 0.56,
            title: 'Plant Spiral',
            author: 'Botanical Subsystem',
            location: 'Courtyard Growth Ring',
            excerpt:
              'The spiral plants lean toward one particular star cluster, suggesting the garden knows the route better than you do.',
            body: 'The spiral plants lean toward one particular star cluster, suggesting the garden knows the route better than you do.\n\nTheir motion is too deliberate for weather and too patient for machinery.\n\nSomething in this level still tracks the sky with devotion.',
          },
        },
        {
          id: 'sci-fi-story-junk',
          name: 'Story Marker · Junk Memory',
          kind: 'prefab',
          position: [-3.6, 1.48, 52.44],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'story-marker', variant: 'red' },
          gameplay: {
            type: 'note',
            markerColor: '#ff6666',
            markerSize: 0.7,
            title: 'Junk Memory',
            author: 'Debris Field Echo',
            location: 'Deep Wasteland',
            excerpt:
              'Deep in the wasteland, the debris resolves into intent: this ruin was not abandoned, it was aimed at the heavens and left mid-sentence.',
            body: 'Deep in the wasteland, the debris resolves into intent: this ruin was not abandoned, it was aimed at the heavens and left mid-sentence.\n\nThe broken shapes form vectors, not rubble.\n\nWhatever failed here was trying to point beyond the room.',
          },
        },
        {
          id: 'sci-fi-command-fin-left',
          name: 'Command Fin Left',
          kind: 'prefab',
          position: [-4.8, 2.18, -3.8],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'command-fin' },
        },
        {
          id: 'sci-fi-command-fin-right',
          name: 'Command Fin Right',
          kind: 'prefab',
          position: [4.8, 2.18, -3.8],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'command-fin' },
        },
        {
          id: 'sci-fi-hanging-light-left',
          name: 'Hanging Light Left',
          kind: 'prefab',
          position: [-3.0, 7.7, -0.9],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'hanging-light' },
        },
        {
          id: 'sci-fi-hanging-light-right',
          name: 'Hanging Light Right',
          kind: 'prefab',
          position: [3.0, 7.7, -0.9],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'hanging-light' },
        },
        {
          id: 'sci-fi-aircon-command',
          name: 'Command Aircon',
          kind: 'asset',
          position: [-10.23, 1.65, -1.3],
          rotation: [0, Math.PI / 2, 0],
          scale: [0.00092, 0.00092, 0.00092],
          visible: true,
          asset: {
            url: '/models/polyhaven/exterior_aircon_unit/exterior_aircon_unit_1k.gltf',
          },
        },
        {
          id: 'sci-fi-support-column-a',
          name: 'Support Column A',
          kind: 'prefab',
          position: [-3.5, 3.68, -2.0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'support-column' },
        },
        {
          id: 'sci-fi-support-column-b',
          name: 'Support Column B',
          kind: 'prefab',
          position: [3.5, 3.68, 2.0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'support-column' },
        },
        {
          id: 'sci-fi-support-column-c',
          name: 'Support Column C',
          kind: 'prefab',
          position: [-3.5, 3.68, 2.0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'support-column' },
        },
        {
          id: 'sci-fi-support-column-d',
          name: 'Support Column D',
          kind: 'prefab',
          position: [3.5, 3.68, -2.0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'support-column' },
        },
        {
          id: 'sci-fi-interior-archway',
          name: 'Interior Archway',
          kind: 'prefab',
          position: [0, 0, 3.5],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'interior-archway' },
        },
        {
          id: 'sci-fi-courtyard-pylon-left',
          name: 'Courtyard Pylon Left',
          kind: 'prefab',
          position: [-1.2, 0, 18.52],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'courtyard-pylon' },
        },
        {
          id: 'sci-fi-courtyard-pylon-right',
          name: 'Courtyard Pylon Right',
          kind: 'prefab',
          position: [1.2, 0, 18.52],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'courtyard-pylon' },
        },
        {
          id: 'sci-fi-wasteland-archway',
          name: 'Wasteland Archway',
          kind: 'prefab',
          position: [0, 0, 24.52],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'wasteland-archway' },
        },
        {
          id: 'sci-fi-fountain',
          name: 'Courtyard Fountain',
          kind: 'prefab',
          position: [0, -0.32, 21.52],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'courtyard-fountain' },
        },
        {
          id: 'sci-fi-observation-rig',
          name: 'Observation Rig',
          kind: 'prefab',
          position: [0, 0, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'observation-rig' },
        },
        {
          id: 'sci-fi-courtyard-aircon',
          name: 'Courtyard Utility Unit',
          kind: 'asset',
          position: [4.2, 0.03, 26.22],
          rotation: [0, -1.15, 0],
          scale: [0.0009, 0.0009, 0.0009],
          visible: true,
          asset: {
            url: '/models/polyhaven/exterior_aircon_unit/exterior_aircon_unit_1k.gltf',
          },
        },
        {
          id: 'sci-fi-planter-a',
          name: 'Growth Planter A',
          kind: 'prefab',
          position: [-3.0, 0, 25.52],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'growth-planter' },
        },
        {
          id: 'sci-fi-planter-b',
          name: 'Growth Planter B',
          kind: 'asset',
          position: [3.0, 0, 25.52],
          rotation: [0, 0.6, 0],
          scale: [1, 1, 1],
          visible: true,
          asset: { url: SCI_FI_PLANTER_B_ASSET_URL },
        },
        {
          id: 'sci-fi-planter-c',
          name: 'Growth Planter C',
          kind: 'prefab',
          position: [-3.0, 0, 23.52],
          rotation: [0, 1.2, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'growth-planter' },
        },
        {
          id: 'sci-fi-planter-d',
          name: 'Growth Planter D',
          kind: 'prefab',
          position: [3.0, 0, 23.52],
          rotation: [0, -0.4, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'growth-planter' },
        },
        {
          id: 'sci-fi-bench',
          name: 'Bench Growth',
          kind: 'prefab',
          position: [0, 0, 19.52],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'bench-growth' },
        },
        {
          id: 'sci-fi-monolith-a',
          name: 'Monolith A',
          kind: 'prefab',
          position: [-8.5, 3.48, 53.54],
          rotation: [0, 0, 0],
          scale: [1.2, 7.6, 1.0],
          visible: true,
          prefab: { type: 'wasteland-monolith' },
        },
        {
          id: 'sci-fi-monolith-b',
          name: 'Monolith B',
          kind: 'prefab',
          position: [7.2, 4.28, 58.54],
          rotation: [0, 0, 0],
          scale: [1.5, 9.2, 1.2],
          visible: true,
          prefab: { type: 'wasteland-monolith' },
        },
        {
          id: 'sci-fi-monolith-c',
          name: 'Monolith C',
          kind: 'prefab',
          position: [-2.4, 2.78, 62.04],
          rotation: [0, 0, 0],
          scale: [0.9, 6.2, 0.9],
          visible: true,
          prefab: { type: 'wasteland-monolith' },
        },
        {
          id: 'sci-fi-broken-ring',
          name: 'Broken Ring',
          kind: 'prefab',
          position: [2.8, 3.78, 56.44],
          rotation: [0.28, 0.45, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'broken-ring' },
        },
        {
          id: 'sci-fi-barrel',
          name: 'Wasteland Barrel',
          kind: 'asset',
          position: [5.4, -0.3, 48.44],
          rotation: [0, -0.6, 0],
          scale: [0.001, 0.001, 0.001],
          visible: true,
          asset: { url: '/models/polyhaven/Barrel_01/Barrel_01_1k.gltf' },
        },
        {
          id: 'sci-fi-barrier',
          name: 'Concrete Barrier',
          kind: 'asset',
          position: [-5.8, -0.3, 54.64],
          rotation: [0, 0.35, 0],
          scale: [0.00108, 0.00108, 0.00108],
          visible: true,
          asset: {
            url: '/models/polyhaven/concrete_road_barrier_02/concrete_road_barrier_02_1k.gltf',
          },
        },
      ],
    }
  }

  if (levelId === 'miranda') {
    return {
      levelId,
      version: 1,
      updatedAt: nowIso(),
      settings: {
        level: {
          spawn: {
            position: [0, 4.25, -13.8],
          },
          skyboxPreset: 'observatory',
          features: {
            styles: true,
            starMap: false,
            conversations: false,
            water: false,
            ambientParticles: false,
          },
          style: {
            fog: {
              color: '#080b12',
              density: 0.017,
            },
          },
          lighting: {
            ambientIntensity: 0.38,
            keyLightIntensity: 1.15,
            fillLightIntensity: 0.42,
          },
        },
      },
      nodes: [
        ...createMirandaGroundNodes(),
        {
          id: 'miranda-command-gallery',
          name: 'Command Gallery',
          kind: 'group',
          position: [0, 4.9, -27.5],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
        },
        {
          id: 'miranda-command-gallery-light',
          name: 'Command Gallery Beacon',
          kind: 'light',
          parentId: 'miranda-command-gallery',
          position: [0, 2.8, 3.4],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          light: {
            color: '#e76949',
            intensity: 8,
            distance: 20,
            decay: 2,
          },
        },
        {
          id: 'miranda-cockpit',
          name: 'Cockpit',
          kind: 'group',
          position: [0, 1.6, -17.5],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
        },
        {
          id: 'miranda-cockpit-console',
          name: 'Cockpit Console',
          kind: 'prefab',
          parentId: 'miranda-cockpit',
          position: [0, 0, 0],
          rotation: [0, Math.PI, 0],
          scale: [1.15, 1.15, 1.1],
          visible: true,
          prefab: { type: 'command-console' },
        },
        {
          id: 'miranda-cockpit-panel-left',
          name: 'Cockpit Glow Panel Left',
          kind: 'primitive',
          parentId: 'miranda-cockpit',
          position: [-2.6, 0.65, -2.7],
          rotation: [0.18, 0.36, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [2.1, 0.2, 1.1],
            color: '#1e2e3f',
            emissive: '#92dfff',
            emissiveIntensity: 0.9,
            metalness: 0.88,
            roughness: 0.18,
          },
        },
        {
          id: 'miranda-cockpit-panel-center',
          name: 'Cockpit Glow Panel Center',
          kind: 'primitive',
          parentId: 'miranda-cockpit',
          position: [0, 0.65, -2.7],
          rotation: [0.18, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [2.4, 0.2, 1.1],
            color: '#1e2e3f',
            emissive: '#92dfff',
            emissiveIntensity: 1.0,
            metalness: 0.9,
            roughness: 0.16,
          },
        },
        {
          id: 'miranda-cockpit-panel-right',
          name: 'Cockpit Glow Panel Right',
          kind: 'primitive',
          parentId: 'miranda-cockpit',
          position: [2.6, 0.65, -2.7],
          rotation: [0.18, -0.36, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [2.1, 0.2, 1.1],
            color: '#1e2e3f',
            emissive: '#92dfff',
            emissiveIntensity: 0.9,
            metalness: 0.88,
            roughness: 0.18,
          },
        },
        {
          id: 'miranda-captain-log',
          name: "Story Marker · Captain's Log",
          kind: 'prefab',
          parentId: 'miranda-cockpit',
          position: [-1.35, 0.5, -0.9],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'story-marker', variant: 'cyan' },
          gameplay: {
            type: 'note',
            markerColor: '#9fdcff',
            markerSize: 0.62,
            title: "Captain's Log 45.7.21",
            author: 'Captain Helena Zhao',
            location: 'Cockpit Nav Station',
            excerpt:
              'There is nothing to salvage. Only debris, salt, and the taste of a vanished system.',
            body: "This is Captain Helena Zhao of the salvage vessel Second Breakfast.\n\nMiranda's primary sun went supernova without warning. Inner planets vaporized. Outer planetoids were thrown into cold darkness. We entered the debris field expecting a graveyard and found something worse: a silence that feels arranged.\n\nSome say you can still taste celery salt in the dust. I laughed when I first heard it. I am not laughing now.",
          },
        },
        {
          id: 'miranda-crew-quarters',
          name: 'Crew Quarters',
          kind: 'group',
          position: [-6.15, 1.3, -2.6],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
        },
        {
          id: 'miranda-bunk-port-a',
          name: 'Bunk Port A',
          kind: 'primitive',
          parentId: 'miranda-crew-quarters',
          position: [-1.4, -0.54, -1.6],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [2.3, 0.28, 1],
            color: '#2b3341',
            emissive: '#122030',
            emissiveIntensity: 0.08,
            metalness: 0.58,
            roughness: 0.46,
          },
        },
        {
          id: 'miranda-bunk-port-b',
          name: 'Bunk Port B',
          kind: 'primitive',
          parentId: 'miranda-crew-quarters',
          position: [-1.4, 0.8, -1.6],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [2.3, 0.28, 1],
            color: '#2b3341',
            emissive: '#122030',
            emissiveIntensity: 0.08,
            metalness: 0.58,
            roughness: 0.46,
          },
        },
        {
          id: 'miranda-bunk-starboard-a',
          name: 'Bunk Starboard A',
          kind: 'primitive',
          parentId: 'miranda-crew-quarters',
          position: [-1.4, -0.54, 3.5],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [2.3, 0.28, 1],
            color: '#2b3341',
            emissive: '#122030',
            emissiveIntensity: 0.08,
            metalness: 0.58,
            roughness: 0.46,
          },
        },
        {
          id: 'miranda-bunk-starboard-b',
          name: 'Bunk Starboard B',
          kind: 'primitive',
          parentId: 'miranda-crew-quarters',
          position: [-1.4, 0.8, 3.5],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [2.3, 0.28, 1],
            color: '#2b3341',
            emissive: '#122030',
            emissiveIntensity: 0.08,
            metalness: 0.58,
            roughness: 0.46,
          },
        },
        {
          id: 'miranda-locker-bank',
          name: 'Locker Bank',
          kind: 'primitive',
          parentId: 'miranda-crew-quarters',
          position: [1.45, 0.02, 0.95],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [1.1, 2.4, 6.5],
            color: '#29323d',
            emissive: '#0f1823',
            emissiveIntensity: 0.06,
            metalness: 0.72,
            roughness: 0.34,
          },
        },
        {
          id: 'miranda-crew-note',
          name: 'Story Marker · Medical Watch',
          kind: 'prefab',
          parentId: 'miranda-crew-quarters',
          position: [-1.05, -0.22, 2.5],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'story-marker', variant: 'red' },
          gameplay: {
            type: 'note',
            markerColor: '#ff9d9d',
            markerSize: 0.6,
            title: 'Crew Medical Watch',
            author: 'Dr. Imani Vale',
            location: 'Crew Quarters Locker',
            excerpt:
              'Headaches, nausea, deja vu. Nobody wants to say the symptoms out loud twice.',
            body: 'Three crew reported headaches after handling drone returns from the debris field. Two described dreams of a bar they have never visited. One woke up repeating a drink order in a voice he claims was not his own.\n\nNo abnormalities on scans. No fever. No infection. The fear is the only thing progressing.\n\nRecommendation: limit direct exposure to recovered signal caches, especially any reference to a Bloody Mary and any insistence on pickle prohibition.',
          },
        },
        {
          id: 'miranda-captain-office',
          name: "Captain's Office",
          kind: 'group',
          position: [6.1, 1.3, -3.6],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
        },
        {
          id: 'miranda-captains-desk',
          name: "Captain's Desk",
          kind: 'primitive',
          parentId: 'miranda-captain-office',
          position: [0.45, -0.4, -1.0],
          rotation: [0, 0.08, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [2.1, 0.18, 1.12],
            color: '#5a3c2b',
            emissive: '#24160f',
            emissiveIntensity: 0.04,
            metalness: 0.18,
            roughness: 0.78,
          },
        },
        {
          id: 'miranda-captains-chair',
          name: "Captain's Chair",
          kind: 'primitive',
          parentId: 'miranda-captain-office',
          position: [-0.98, -0.08, -1.25],
          rotation: [0, -0.25, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'cylinder',
            args: [0.58, 0.58, 0.82, 16],
            color: '#3b2f36',
            emissive: '#181116',
            emissiveIntensity: 0.06,
            metalness: 0.26,
            roughness: 0.74,
          },
        },
        {
          id: 'miranda-safe',
          name: 'Recipe Safe',
          kind: 'primitive',
          parentId: 'miranda-captain-office',
          position: [1.25, 0.12, -2.95],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [1.05, 1.32, 0.96],
            color: '#2b3138',
            emissive: '#12181d',
            emissiveIntensity: 0.05,
            metalness: 0.82,
            roughness: 0.28,
          },
        },
        {
          id: 'miranda-first-officer-note',
          name: 'Story Marker · First Officer',
          kind: 'prefab',
          parentId: 'miranda-captain-office',
          position: [0.7, -0.24, -0.5],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'story-marker', variant: 'amber' },
          gameplay: {
            type: 'note',
            markerColor: '#e7c89d',
            markerSize: 0.58,
            title: 'Private Memorandum',
            author: 'First Officer Soren Pike',
            location: "Captain's Office Desk",
            excerpt:
              'The captain looks composed until someone mentions drinks, dreams, or card players.',
            body: 'The captain has not slept properly in eleven cycles. She denies it, but the evidence is in the way she freezes whenever recovered transcripts mention the saloon.\n\nTwice now she has asked whether anyone else has seen three old men through the bridge glass. There was nobody there. On the second occasion she also asked whether the ship kept a safe for paper records.\n\nIt does now.',
          },
        },
        {
          id: 'miranda-vault-fragment',
          name: 'Story Marker · Vault Fragment',
          kind: 'prefab',
          parentId: 'miranda-captain-office',
          position: [1.9, -0.12, -2.95],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'story-marker', variant: 'red' },
          gameplay: {
            type: 'note',
            markerColor: '#ff6d8e',
            markerSize: 0.58,
            title: 'Vault Fragment: Recipe Lockbox',
            author: 'Recovered hardcopy, access restricted',
            location: "Captain's Safe",
            excerpt:
              'The page keeps moving. The phrase keeps returning. The paper smells faintly of tomato, iron, and smoke.',
            body: "Cross-reference from the mechanical observer and the old man's account suggests a causality nexus formed around a drink completed at the instant of Miranda's destruction.\n\nHardcopy fragment secured in captain's vault after digital copies exhibited instability. Crew instructed not to vocalize the activation phrase aloud.\n\nFragment note: \"Bloody Mary, no pickles, make it a double.\"\n\nIf this page is found outside the safe again, burn it and do not discuss the ash.",
          },
        },
        {
          id: 'miranda-airlock',
          name: 'Airlock Return',
          kind: 'group',
          position: [0, 1.0, 6.6],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
        },
        {
          id: 'miranda-return-portal',
          name: 'Return to Observatory',
          kind: 'prefab',
          parentId: 'miranda-airlock',
          position: [0, 0, 0],
          rotation: [0, 0, 0],
          scale: [0.95, 0.95, 0.95],
          visible: true,
          prefab: { type: 'portal-apparatus' },
          gameplay: {
            type: 'portal',
            targetLevelId: 'observatory',
            markerColor: '#7fd3ff',
            markerSize: 1.05,
          },
        },
        {
          id: 'miranda-engine-room',
          name: 'Engine Room',
          kind: 'group',
          position: [0, 1.4, 16.5],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
        },
        {
          id: 'miranda-engine-core',
          name: 'Engine Core',
          kind: 'primitive',
          parentId: 'miranda-engine-room',
          position: [0, 0.35, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'cylinder',
            args: [1.1, 1.4, 3.6, 18],
            color: '#5a2d24',
            emissive: '#ffb56b',
            emissiveIntensity: 0.95,
            metalness: 0.86,
            roughness: 0.24,
          },
        },
        {
          id: 'miranda-engine-column-a',
          name: 'Engine Column A',
          kind: 'primitive',
          parentId: 'miranda-engine-room',
          position: [-3.6, 0.1, -0.9],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'cylinder',
            args: [0.48, 0.48, 3.0, 14],
            color: '#46313a',
            emissive: '#181116',
            emissiveIntensity: 0.04,
            metalness: 0.82,
            roughness: 0.28,
          },
        },
        {
          id: 'miranda-engine-column-b',
          name: 'Engine Column B',
          kind: 'primitive',
          parentId: 'miranda-engine-room',
          position: [-1.2, 0.1, -0.9],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'cylinder',
            args: [0.48, 0.48, 3.0, 14],
            color: '#46313a',
            emissive: '#181116',
            emissiveIntensity: 0.04,
            metalness: 0.82,
            roughness: 0.28,
          },
        },
        {
          id: 'miranda-engine-column-c',
          name: 'Engine Column C',
          kind: 'primitive',
          parentId: 'miranda-engine-room',
          position: [1.2, 0.1, -0.9],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'cylinder',
            args: [0.48, 0.48, 3.0, 14],
            color: '#46313a',
            emissive: '#181116',
            emissiveIntensity: 0.04,
            metalness: 0.82,
            roughness: 0.28,
          },
        },
        {
          id: 'miranda-engine-column-d',
          name: 'Engine Column D',
          kind: 'primitive',
          parentId: 'miranda-engine-room',
          position: [3.6, 0.1, -0.9],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'cylinder',
            args: [0.48, 0.48, 3.0, 14],
            color: '#46313a',
            emissive: '#181116',
            emissiveIntensity: 0.04,
            metalness: 0.82,
            roughness: 0.28,
          },
        },
        {
          id: 'miranda-engine-note',
          name: 'Story Marker · Engineering Memo',
          kind: 'prefab',
          parentId: 'miranda-engine-room',
          position: [2.55, -0.2, -0.8],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'story-marker', variant: 'amber' },
          gameplay: {
            type: 'note',
            markerColor: '#ffb36d',
            markerSize: 0.62,
            title: 'Engineering Memo 8.15',
            author: 'Chief Engineer Mara Quill',
            location: 'Engine Room Control Deck',
            excerpt:
              'The ship is humming in sympathy with transmissions that should no longer exist.',
            body: "Reactor output remains nominal, but the harmonic drift is wrong. Every time we pass through a dense pocket of Miranda ash, the engine room resonates with carrier bands matching the dead system's final RF burst.\n\nIt sounds like traffic stacked above an atmosphere that is no longer there. Queue chatter. Clearance loops. Repeated holds.\n\nI have shut down three relays and the sound still comes through the deck.",
          },
        },
        {
          id: 'miranda-medbay',
          name: 'Medbay',
          kind: 'group',
          position: [-11.1, 1.2, 12.6],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
        },
        {
          id: 'miranda-med-pod-a',
          name: 'Med Pod A',
          kind: 'primitive',
          parentId: 'miranda-medbay',
          position: [-1.7, 0.82, -3.0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [1.2, 1.4, 3.6],
            color: '#6da8bf',
            emissive: '#8de0ff',
            emissiveIntensity: 0.4,
            metalness: 0.28,
            roughness: 0.16,
            transparent: true,
            opacity: 0.72,
          },
        },
        {
          id: 'miranda-med-pod-b',
          name: 'Med Pod B',
          kind: 'primitive',
          parentId: 'miranda-medbay',
          position: [1.3, 0.82, -3.0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [1.2, 1.4, 3.6],
            color: '#6da8bf',
            emissive: '#8de0ff',
            emissiveIntensity: 0.4,
            metalness: 0.28,
            roughness: 0.16,
            transparent: true,
            opacity: 0.72,
          },
        },
        {
          id: 'miranda-med-pod-c',
          name: 'Med Pod C',
          kind: 'primitive',
          parentId: 'miranda-medbay',
          position: [-1.7, 0.82, 4.0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [1.2, 1.4, 3.6],
            color: '#6da8bf',
            emissive: '#8de0ff',
            emissiveIntensity: 0.4,
            metalness: 0.28,
            roughness: 0.16,
            transparent: true,
            opacity: 0.72,
          },
        },
        {
          id: 'miranda-med-pod-d',
          name: 'Med Pod D',
          kind: 'primitive',
          parentId: 'miranda-medbay',
          position: [1.3, 0.82, 4.0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [1.2, 1.4, 3.6],
            color: '#6da8bf',
            emissive: '#8de0ff',
            emissiveIntensity: 0.4,
            metalness: 0.28,
            roughness: 0.16,
            transparent: true,
            opacity: 0.72,
          },
        },
        {
          id: 'miranda-medbay-note',
          name: 'Story Marker · Quarantine',
          kind: 'prefab',
          parentId: 'miranda-medbay',
          position: [-1.8, -0.12, -0.4],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'story-marker', variant: 'cyan' },
          gameplay: {
            type: 'note',
            markerColor: '#8de0ff',
            markerSize: 0.6,
            title: 'Quarantine Bay Slip',
            author: 'Dr. Imani Vale',
            location: 'Medbay Cryo Pod',
            excerpt:
              'The sleepers are not dead. The ship still refuses to classify them as living.',
            body: "We sealed three crew inside the aft medbay after the Miranda ash dreams escalated into waking fugues. They answer to their names, but only after a delay, as if translating from somewhere farther away.\n\nTheir body temperatures fall whenever the Bloody Mary phrase is spoken near the pods. The glass frosts from the inside first.\n\nI have ordered the quarantine lamps to stay red until somebody can explain why the EEG spikes match the ship's own telemetry.",
          },
        },
        {
          id: 'miranda-mess',
          name: 'Mess Hall',
          kind: 'group',
          position: [-10.8, 1.2, 30.8],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
        },
        {
          id: 'miranda-mess-table-a',
          name: 'Mess Table A',
          kind: 'primitive',
          parentId: 'miranda-mess',
          position: [-0.6, -0.48, -3.2],
          rotation: [0, 0.1, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [2.8, 0.18, 1.2],
            color: '#5d4638',
            emissive: '#241912',
            emissiveIntensity: 0.04,
            metalness: 0.18,
            roughness: 0.82,
          },
        },
        {
          id: 'miranda-mess-table-b',
          name: 'Mess Table B',
          kind: 'primitive',
          parentId: 'miranda-mess',
          position: [1.6, -0.48, 2.4],
          rotation: [0, -0.2, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [2.4, 0.18, 1.2],
            color: '#5d4638',
            emissive: '#241912',
            emissiveIntensity: 0.04,
            metalness: 0.18,
            roughness: 0.82,
          },
        },
        {
          id: 'miranda-mess-counter',
          name: 'Mess Counter',
          kind: 'primitive',
          parentId: 'miranda-mess',
          position: [-2.8, -0.18, -1.0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [1.2, 2.04, 5.8],
            color: '#3f2d29',
            emissive: '#160e0d',
            emissiveIntensity: 0.06,
            metalness: 0.46,
            roughness: 0.54,
          },
        },
        {
          id: 'miranda-mess-note',
          name: 'Story Marker · Mess Ledger',
          kind: 'prefab',
          parentId: 'miranda-mess',
          position: [-0.6, -0.18, -1.6],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'story-marker', variant: 'amber' },
          gameplay: {
            type: 'note',
            markerColor: '#ffc584',
            markerSize: 0.6,
            title: 'Mess Ledger Addendum',
            author: 'Steward Callum Reef',
            location: 'Galley Service Counter',
            excerpt:
              'We ran out of clean water before we ran out of stories about the bar.',
            body: 'Nobody eats in the mess unless the speakers are playing static. If the channels are quiet, people start hearing the card table again.\n\nThe bowls rattle whenever we cross a dense ash current. Plates slide toward the aft corridor as if the ship itself leans toward Miranda.\n\nI locked the pantry and still found celery salt on the floor this morning.',
          },
        },
        {
          id: 'miranda-chapel',
          name: 'Chapel',
          kind: 'group',
          position: [10.8, 1.2, 14.6],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
        },
        {
          id: 'miranda-chapel-monolith-a',
          name: 'Chapel Monolith A',
          kind: 'prefab',
          parentId: 'miranda-chapel',
          position: [-1.6, 0.8, -1.8],
          rotation: [0, 0.12, 0],
          scale: [1.1, 4, 1.1],
          visible: true,
          prefab: { type: 'wasteland-monolith' },
        },
        {
          id: 'miranda-chapel-monolith-b',
          name: 'Chapel Monolith B',
          kind: 'prefab',
          parentId: 'miranda-chapel',
          position: [1.6, 1, -2.2],
          rotation: [0, -0.14, 0],
          scale: [1.1, 4.4, 1.1],
          visible: true,
          prefab: { type: 'wasteland-monolith' },
        },
        {
          id: 'miranda-chapel-altar',
          name: 'Chapel Altar',
          kind: 'primitive',
          parentId: 'miranda-chapel',
          position: [0, -0.28, 3.8],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [3.4, 1.84, 1.3],
            color: '#332934',
            emissive: '#b991ff',
            emissiveIntensity: 0.22,
            metalness: 0.36,
            roughness: 0.58,
          },
        },
        {
          id: 'miranda-brig',
          name: 'Brig',
          kind: 'group',
          position: [10.8, 1.2, 32.2],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
        },
        {
          id: 'miranda-brig-cell-a',
          name: 'Brig Cell A',
          kind: 'primitive',
          parentId: 'miranda-brig',
          position: [-1.4, 0.2, -2.2],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [1.1, 2.8, 4.2],
            color: '#3f3034',
            emissive: '#150f12',
            emissiveIntensity: 0.05,
            metalness: 0.6,
            roughness: 0.42,
          },
        },
        {
          id: 'miranda-brig-cell-b',
          name: 'Brig Cell B',
          kind: 'primitive',
          parentId: 'miranda-brig',
          position: [2.2, 0.2, -2.2],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [1.1, 2.8, 4.2],
            color: '#3f3034',
            emissive: '#150f12',
            emissiveIntensity: 0.05,
            metalness: 0.6,
            roughness: 0.42,
          },
        },
        {
          id: 'miranda-brig-cell-c',
          name: 'Brig Cell C',
          kind: 'primitive',
          parentId: 'miranda-brig',
          position: [-1.4, 0.2, 5.4],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [1.1, 2.8, 4.2],
            color: '#3f3034',
            emissive: '#150f12',
            emissiveIntensity: 0.05,
            metalness: 0.6,
            roughness: 0.42,
          },
        },
        {
          id: 'miranda-brig-cell-d',
          name: 'Brig Cell D',
          kind: 'primitive',
          parentId: 'miranda-brig',
          position: [2.2, 0.2, 5.4],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [1.1, 2.8, 4.2],
            color: '#3f3034',
            emissive: '#150f12',
            emissiveIntensity: 0.05,
            metalness: 0.6,
            roughness: 0.42,
          },
        },
        {
          id: 'miranda-brig-desk',
          name: 'Brig Desk',
          kind: 'primitive',
          parentId: 'miranda-brig',
          position: [0.3, -0.48, 9.8],
          rotation: [0, 0.08, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [2.4, 1.44, 1.2],
            color: '#4a3732',
            emissive: '#1b1310',
            emissiveIntensity: 0.04,
            metalness: 0.22,
            roughness: 0.8,
          },
        },
        {
          id: 'miranda-brig-note',
          name: 'Story Marker · Brig Confession',
          kind: 'prefab',
          parentId: 'miranda-brig',
          position: [2.0, -0.12, -0.6],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'story-marker', variant: 'red' },
          gameplay: {
            type: 'note',
            markerColor: '#ff8ea6',
            markerSize: 0.6,
            title: 'Brig Confession',
            author: 'Unnamed detainee',
            location: 'Detention Cell 02',
            excerpt:
              'I was not trying to open the safe. I was trying to put the page back.',
            body: "They locked me in the brig because I kept leaving the corridor at night and waking up near the captain's office with soot under my nails.\n\nThe truth is smaller and worse: every time I close my eyes, I can hear a voice asking me to return a recipe card to its proper era.\n\nThe bars hum when the engines drift. The hum knows my name.",
          },
        },
        {
          id: 'miranda-cargo-hold',
          name: 'Cargo Hold',
          kind: 'group',
          position: [0, 1.2, 35.2],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
        },
        {
          id: 'miranda-cargo-stack-a',
          name: 'Cargo Stack A',
          kind: 'primitive',
          parentId: 'miranda-cargo-hold',
          position: [-2.8, -0.25, -1.6],
          rotation: [0, 0.1, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [3.2, 1.9, 3.4],
            color: '#564136',
            emissive: '#241a13',
            emissiveIntensity: 0.04,
            metalness: 0.16,
            roughness: 0.86,
          },
        },
        {
          id: 'miranda-cargo-stack-b',
          name: 'Cargo Stack B',
          kind: 'primitive',
          parentId: 'miranda-cargo-hold',
          position: [3.8, 0.15, 2.9],
          rotation: [0, -0.15, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [2.6, 2.7, 2.8],
            color: '#5a4334',
            emissive: '#241a13',
            emissiveIntensity: 0.04,
            metalness: 0.16,
            roughness: 0.86,
          },
        },
        {
          id: 'miranda-cargo-stack-c',
          name: 'Cargo Stack C',
          kind: 'primitive',
          parentId: 'miranda-cargo-hold',
          position: [0.2, -0.5, 9.0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [4.6, 1.4, 2.6],
            color: '#5a4334',
            emissive: '#241a13',
            emissiveIntensity: 0.04,
            metalness: 0.16,
            roughness: 0.86,
          },
        },
        {
          id: 'miranda-cargo-stack-d',
          name: 'Cargo Stack D',
          kind: 'primitive',
          parentId: 'miranda-cargo-hold',
          position: [-4.6, -0.42, -6.8],
          rotation: [0, 0.2, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [2.2, 1.56, 2.2],
            color: '#5a4334',
            emissive: '#241a13',
            emissiveIntensity: 0.04,
            metalness: 0.16,
            roughness: 0.86,
          },
        },
        {
          id: 'miranda-observation-gallery',
          name: 'Observation Gallery',
          kind: 'group',
          position: [-10.8, 4.9, 8.4],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
        },
        {
          id: 'miranda-observation-light',
          name: 'Observation Light',
          kind: 'light',
          parentId: 'miranda-observation-gallery',
          position: [0, 2.3, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          light: {
            color: '#8adff5',
            intensity: 4.6,
            distance: 15,
            decay: 2,
          },
        },
        {
          id: 'miranda-archive-gallery',
          name: 'Archive Gallery',
          kind: 'group',
          position: [10.8, 4.9, 10.8],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
        },
        {
          id: 'miranda-server-bank-a',
          name: 'Server Bank A',
          kind: 'primitive',
          parentId: 'miranda-archive-gallery',
          position: [-1.4, 0.2, -9.2],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [1.4, 2.6, 3.2],
            color: '#202634',
            emissive: '#7dc8ff',
            emissiveIntensity: 0.28,
            metalness: 0.86,
            roughness: 0.22,
          },
        },
        {
          id: 'miranda-server-bank-b',
          name: 'Server Bank B',
          kind: 'primitive',
          parentId: 'miranda-archive-gallery',
          position: [2.4, 0.2, -9.2],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [1.4, 2.6, 3.2],
            color: '#202634',
            emissive: '#7dc8ff',
            emissiveIntensity: 0.28,
            metalness: 0.86,
            roughness: 0.22,
          },
        },
        {
          id: 'miranda-server-bank-c',
          name: 'Server Bank C',
          kind: 'primitive',
          parentId: 'miranda-archive-gallery',
          position: [-1.4, 0.2, 3.0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [1.4, 2.6, 3.2],
            color: '#202634',
            emissive: '#7dc8ff',
            emissiveIntensity: 0.28,
            metalness: 0.86,
            roughness: 0.22,
          },
        },
        {
          id: 'miranda-server-bank-d',
          name: 'Server Bank D',
          kind: 'primitive',
          parentId: 'miranda-archive-gallery',
          position: [2.4, 0.2, 3.0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [1.4, 2.6, 3.2],
            color: '#202634',
            emissive: '#7dc8ff',
            emissiveIntensity: 0.28,
            metalness: 0.86,
            roughness: 0.22,
          },
        },
        {
          id: 'miranda-server-bank-e',
          name: 'Server Bank E',
          kind: 'primitive',
          parentId: 'miranda-archive-gallery',
          position: [0.5, 0.2, 13.2],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          primitive: {
            geometry: 'box',
            args: [4.8, 2.6, 1.6],
            color: '#202634',
            emissive: '#7dc8ff',
            emissiveIntensity: 0.32,
            metalness: 0.86,
            roughness: 0.22,
          },
        },
        {
          id: 'miranda-archive-light',
          name: 'Archive Light',
          kind: 'light',
          parentId: 'miranda-archive-gallery',
          position: [0, 2.1, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          light: {
            color: '#7dc8ff',
            intensity: 5,
            distance: 16,
            decay: 2,
          },
        },
        {
          id: 'miranda-archive-note',
          name: 'Story Marker · Archive Index',
          kind: 'prefab',
          parentId: 'miranda-archive-gallery',
          position: [1.8, 0.12, -1.4],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'story-marker', variant: 'magenta' },
          gameplay: {
            type: 'note',
            markerColor: '#cba7ff',
            markerSize: 0.6,
            title: 'Archive Index: Recovered Echoes',
            author: 'Signal Archivist Nila Serrin',
            location: 'Upper Data Gallery',
            excerpt:
              'Each copied transcript diverges the second time it is opened.',
            body: 'The upper archive is no longer storing files. It is growing variants.\n\nOpen one Miranda transcript and you receive an account. Open it again and the witness order changes. Open it a third time and there is a fourth witness seated at the table.\n\nI moved the worst logs to the upper stacks and disconnected them from the main grid. The lights in this gallery still blink in answers.',
          },
        },
      ],
    }
  }

  if (levelId === 'observatory') {
    return {
      levelId,
      version: 1,
      updatedAt: nowIso(),
      settings: {
        level: {
          presets: {
            atmosphere: 'moon-archive',
            audio: 'courtyard-breeze',
          },
          spawn: {
            position: [-137.2, 20, -49.5],
          },
          features: {
            ocean: true,
            vegetation: true,
            fireflies: true,
            starMap: true,
            conversations: true,
            styles: true,
          },
          style: {
            preset: 'monument',
            enabled: true,
            fog: {
              color: '#596784',
              density: 0.00075,
            },
            colorGrading: {
              saturation: 0.96,
              contrast: 1.08,
              brightness: 0.91,
              warmth: 0.88,
            },
            bloom: {
              intensity: 0.18,
              threshold: 0.9,
            },
          },
          lighting: {
            ambientIntensity: 7.2,
            sunIntensity: 0.42,
            fillIntensity: 0.26,
            fallbackAmbientIntensity: 4,
            fallbackMoonlightIntensity: 0.62,
            fallbackFillLightIntensity: 0.24,
          },
        },
        observatory: {
          ocean: {
            size: {
              width: 4000,
              height: 4000,
            },
            enableRising: true,
            initialLevel: -2,
            targetLevel: 5,
            riseRate: 0.01,
            enableAnimation: true,
            underwaterFogDensity: 0.1,
            underwaterFogColor: 533536,
            surfaceFogDensity: 0.001,
          },
        },
      },
      nodes: [
        ...createObservatoryGroundNodes(),
        {
          id: 'observatory-arrival-hub',
          name: 'Arrival Hub',
          kind: 'group',
          position: [-137.2, 20.0, -49.5],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
        },
        {
          id: 'observatory-arrival-bench',
          name: 'Arrival Bench',
          kind: 'prefab',
          parentId: 'observatory-arrival-hub',
          position: [-1.6, 0.1, 4.8],
          rotation: [0, -0.4, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'bench-growth' },
        },
        {
          id: 'observatory-arrival-pylon-left',
          name: 'Arrival Pylon Left',
          kind: 'prefab',
          parentId: 'observatory-arrival-hub',
          position: [-5.6, 0, 8.6],
          rotation: [0, 0.18, 0],
          scale: [1, 1.15, 1],
          visible: true,
          prefab: { type: 'courtyard-pylon' },
        },
        {
          id: 'observatory-arrival-pylon-right',
          name: 'Arrival Pylon Right',
          kind: 'prefab',
          parentId: 'observatory-arrival-hub',
          position: [4.8, 0, 8.2],
          rotation: [0, -0.14, 0],
          scale: [1, 1.1, 1],
          visible: true,
          prefab: { type: 'courtyard-pylon' },
        },
        {
          id: 'observatory-sci-fi-portal',
          name: 'Portal to Command Room',
          kind: 'prefab',
          parentId: 'observatory-arrival-hub',
          position: [0.6, 0.1, 11.6],
          rotation: [0, Math.PI, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'portal-apparatus' },
          gameplay: {
            type: 'portal',
            targetLevelId: 'sci-fi-room',
            markerColor: '#8fd8ff',
            markerSize: 1.2,
          },
        },
        {
          id: 'observatory-arrival-note',
          name: 'Story Marker · Arrival',
          kind: 'prefab',
          parentId: 'observatory-arrival-hub',
          position: [-4.6, 0.7, 3.1],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'story-marker', variant: 'cyan' },
          gameplay: {
            type: 'note',
            markerColor: '#7ecbff',
            markerSize: 0.64,
            title: 'Arrival Log',
            author: 'Survey Cartographer',
            location: 'Observatory Landing',
            excerpt:
              'The observatory does not greet visitors with walls. It greets them with horizon, wind, and a suggestion to keep walking upward.',
            body: 'The observatory does not greet visitors with walls. It greets them with horizon, wind, and a suggestion to keep walking upward.\n\nEvery structure here behaves less like shelter and more like orientation.\n\nEven the path feels like an instrument laid across the hillside.',
          },
        },
        {
          id: 'observatory-courtyard',
          name: 'Courtyard Core',
          kind: 'group',
          position: [-118, 22.2, -18],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
        },
        {
          id: 'observatory-fountain',
          name: 'Star Fountain',
          kind: 'prefab',
          parentId: 'observatory-courtyard',
          position: [0, 0, 0],
          rotation: [0, 0, 0],
          scale: [1.2, 1.2, 1.2],
          visible: true,
          prefab: { type: 'courtyard-fountain' },
        },
        {
          id: 'observatory-planter-north',
          name: 'Planter North',
          kind: 'prefab',
          parentId: 'observatory-courtyard',
          position: [0, 0, -7.2],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'growth-planter' },
        },
        {
          id: 'observatory-planter-east',
          name: 'Planter East',
          kind: 'prefab',
          parentId: 'observatory-courtyard',
          position: [7.2, 0, 0],
          rotation: [0, Math.PI / 2, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'growth-planter' },
        },
        {
          id: 'observatory-planter-south',
          name: 'Planter South',
          kind: 'prefab',
          parentId: 'observatory-courtyard',
          position: [0, 0, 7.2],
          rotation: [0, Math.PI, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'growth-planter' },
        },
        {
          id: 'observatory-planter-west',
          name: 'Planter West',
          kind: 'prefab',
          parentId: 'observatory-courtyard',
          position: [-7.2, 0, 0],
          rotation: [0, -Math.PI / 2, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'growth-planter' },
        },
        {
          id: 'observatory-archway',
          name: 'Courtyard Archway',
          kind: 'prefab',
          parentId: 'observatory-courtyard',
          position: [0, 0, -12.8],
          rotation: [0, 0, 0],
          scale: [1.3, 1.2, 1.1],
          visible: true,
          prefab: { type: 'interior-archway' },
        },
        {
          id: 'observatory-courtyard-note',
          name: 'Story Marker · Fountain',
          kind: 'prefab',
          parentId: 'observatory-courtyard',
          position: [2.4, 0.8, 1.8],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'story-marker', variant: 'amber' },
          gameplay: {
            type: 'note',
            markerColor: '#ffd27a',
            markerSize: 0.6,
            title: 'Fountain Calibration',
            author: 'Night Shift Keeper',
            location: 'Courtyard Core',
            excerpt:
              'The fountain is not decorative. It trains the eye to recognize constellations in motion before night fully arrives.',
            body: 'The fountain is not decorative. It trains the eye to recognize constellations in motion before night fully arrives.\n\nWater gives the sky a second surface, one closer to the hands.\n\nStudents learned the heavens here by watching them ripple first.',
          },
        },
        {
          id: 'observatory-overlook',
          name: 'Overlook Platform',
          kind: 'group',
          position: [-89, 27.8, 38],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
        },
        {
          id: 'observatory-rig',
          name: 'Observation Rig',
          kind: 'prefab',
          parentId: 'observatory-overlook',
          position: [0, 0, 0],
          rotation: [0, 0.45, 0],
          scale: [1.2, 1.2, 1.2],
          visible: true,
          prefab: { type: 'observation-rig' },
        },
        {
          id: 'observatory-overlook-column-a',
          name: 'Overlook Column A',
          kind: 'prefab',
          parentId: 'observatory-overlook',
          position: [-4.8, 0, -4.2],
          rotation: [0, 0.1, 0],
          scale: [1, 1.35, 1],
          visible: true,
          prefab: { type: 'support-column' },
        },
        {
          id: 'observatory-overlook-column-b',
          name: 'Overlook Column B',
          kind: 'prefab',
          parentId: 'observatory-overlook',
          position: [4.8, 0, -4.2],
          rotation: [0, -0.08, 0],
          scale: [1, 1.35, 1],
          visible: true,
          prefab: { type: 'support-column' },
        },
        {
          id: 'observatory-overlook-light',
          name: 'Overlook Beacon',
          kind: 'light',
          parentId: 'observatory-overlook',
          position: [0, 3.4, 0.4],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          light: {
            color: '#8fd8ff',
            intensity: 12,
            distance: 24,
            decay: 2,
          },
        },
        {
          id: 'observatory-overlook-note',
          name: 'Story Marker · Telescope',
          kind: 'prefab',
          parentId: 'observatory-overlook',
          position: [2.8, 1.0, -1.6],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
          visible: true,
          prefab: { type: 'story-marker', variant: 'magenta' },
          gameplay: {
            type: 'note',
            markerColor: '#ff8cff',
            markerSize: 0.62,
            title: 'Overlook Procedure',
            author: 'Apprentice Astronomer',
            location: 'Observation Platform',
            excerpt:
              'Before touching the rig, breathe long enough for the horizon to stop moving. The machine prefers a quiet witness.',
            body: 'Before touching the rig, breathe long enough for the horizon to stop moving. The machine prefers a quiet witness.\n\nIt magnifies what the eye brings to it.\n\nImpatience turns every constellation into noise.',
          },
        },
      ],
    }
  }

  return {
    levelId,
    version: 1,
    updatedAt: nowIso(),
    nodes: [],
  }
}
