import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
	terrainRuntimeSceneIds,
	terrainRuntimeScenes,
} from "../src/game/terrain/terrainRuntimeCatalog.js";

const writeRequested = process.argv.includes("--write");
const checkRequested = process.argv.includes("--check");
const errors: string[] = [];
const appRoot = fileURLToPath(new URL("..", import.meta.url));
const generatedTerrainRuntimePath = resolve(
	appRoot,
	"src/game/generated/terrainRuntime.ts",
);
const expectedGeneratedTerrainRuntime = terrainRuntimeModuleSource();
const existingGeneratedTerrainRuntime = existsSync(generatedTerrainRuntimePath)
	? readFileSync(generatedTerrainRuntimePath, "utf8")
	: "";

if (existingGeneratedTerrainRuntime !== expectedGeneratedTerrainRuntime) {
	if (writeRequested) {
		writeFileSync(generatedTerrainRuntimePath, expectedGeneratedTerrainRuntime);
		console.log("Updated src/game/generated/terrainRuntime.ts.");
	} else {
		errors.push(
			"src/game/generated/terrainRuntime.ts is stale. Run `pnpm --dir apps/game.megameal cook:terrain -- --write` to update the generic generated terrain runtime wrapper.",
		);
	}
} else if (writeRequested) {
	console.log("src/game/generated/terrainRuntime.ts is up to date.");
}

if (errors.length > 0) {
	reportErrorsAndExit();
}

const { defaultRuntimeSceneManifests } = await import(
	"../src/game/levels/index.js"
);

for (const runtimeSceneId of terrainRuntimeSceneIds) {
	const terrain = terrainRuntimeScenes[runtimeSceneId];
	const manifest = defaultRuntimeSceneManifests.find(
		(candidate) => candidate.id === runtimeSceneId,
	);

	if (!manifest) {
		errors.push(`terrain runtime scene "${runtimeSceneId}" has no manifest.`);
		continue;
	}

	const manifestTerrainPackageIds = new Set(
		(manifest.terrainPackages ?? []).map((terrainPackage) => terrainPackage.id),
	);
	const requiredTerrainPackageIds = new Set(
		manifest.readiness.requiredTerrainPackageIds ?? [],
	);
	const oldCollisionStableIds = new Set(
		manifest.readiness.requiredCollisionStableIds ?? [],
	);
	const oldWalkableStableIds = new Set(
		manifest.readiness.requiredWalkableStableIds ?? [],
	);
	const levelStableIds = new Set(
		manifest.level.instances.map((instance) => instance.stableId),
	);

	for (const packageId of terrain.readiness.requiredTerrainPackageIds) {
		if (!manifestTerrainPackageIds.has(packageId)) {
			errors.push(
				`manifest "${runtimeSceneId}" is missing terrain package "${packageId}".`,
			);
		}

		if (!requiredTerrainPackageIds.has(packageId)) {
			errors.push(
				`manifest "${runtimeSceneId}" readiness is missing terrain package "${packageId}".`,
			);
		}
	}

	for (const terrainPackage of terrain.terrainPackages) {
		if (terrainPackage.materialSets.length === 0) {
			errors.push(
				`terrain package "${terrainPackage.id}" has no material sets.`,
			);
		}

		if (terrainPackage.startupChunkStableIds.length === 0) {
			errors.push(
				`terrain package "${terrainPackage.id}" has no startup chunks.`,
			);
		}

		for (const chunk of terrainPackage.chunks) {
			if (!levelStableIds.has(chunk.stableId)) {
				errors.push(
					`terrain package "${terrainPackage.id}" chunk "${chunk.stableId}" has no level instance.`,
				);
			}

			if (oldCollisionStableIds.has(chunk.stableId)) {
				errors.push(
					`terrain package "${terrainPackage.id}" chunk "${chunk.stableId}" is still listed in requiredCollisionStableIds.`,
				);
			}

			if (oldWalkableStableIds.has(chunk.stableId)) {
				errors.push(
					`terrain package "${terrainPackage.id}" chunk "${chunk.stableId}" is still listed in requiredWalkableStableIds.`,
				);
			}
		}
	}
}

if (errors.length > 0) {
	reportErrorsAndExit();
} else {
	console.log(
		`Terrain cook/drift validation passed for ${terrainRuntimeSceneIds.length} runtime scenes${checkRequested ? " in check mode" : ""}.`,
	);
}

function terrainRuntimeModuleSource(): string {
	return `// @generated by terrainCook.runtimeModule.v1
// Source: TerrainImportCookContract. Do not edit by hand.

export {
\tgetTerrainRuntimeSceneData,
\tterrainLevelInstancesForRuntimeScene,
\tterrainPackagesForRuntimeScene,
\tterrainReadinessForRuntimeScene,
\tterrainRuntimeSceneIds,
\tterrainRuntimeScenes,
\tyggdrasilTerrainPackageId,
} from "../terrain/terrainRuntimeCatalog.js";
export type { TerrainRuntimeSceneId } from "../terrain/terrainRuntimeCatalog.js";
`;
}

function reportErrorsAndExit(): void {
	console.error("Terrain cook/drift validation failed:");
	for (const error of errors) {
		console.error(`- ${error}`);
	}
	process.exitCode = 1;
}
