import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { buildLevelEditorAiApplyPlanQueueEntry } from "../src/app/editor/levelEditorAiAssetLabModel.js";
import { buildAuthoringSaveTransaction } from "../src/app/editor/levelEditorAuthoringClient.js";
import { buildLevelEditorWorkspaceModel } from "../src/app/editor/levelEditorWorkspaceModel.js";
import type { EditorAiApplyToSelectionPlan } from "../src/game/editor/ai/index.js";
import {
	LEVEL_EDITOR_MISSING_FILE_HASH,
	type LevelEditorAuthoringOperationData,
	type LevelEditorAuthoringSaveTargetData,
	type LevelEditorAuthoringSaveTransactionData,
	buildLevelEditorAuthoringSaveWritePlan,
	buildLevelEditorOwnerRegistry,
	hashLevelEditorAuthoringFileContent,
} from "../src/game/editor/authoring/index.js";
import { saveLevelEditorAuthoringTransaction } from "../src/game/editor/authoring/persistence.js";
import { defaultRuntimeSceneManifests } from "../src/game/levels/index.js";
import {
	authoringTargetStatus,
	handleLevelEditorAuthoringPersistenceRequest,
} from "../src/pages/api/editor/authoring/_shared.js";

const registry = buildLevelEditorOwnerRegistry();

assertEqual(
	registry.runtimeSceneIds.length,
	defaultRuntimeSceneManifests.length,
	"Expected owner registry to be derived from the runtime scene catalog.",
);

for (const manifest of defaultRuntimeSceneManifests) {
	const targets = registry.targets.filter(
		(target) => target.runtimeSceneId === manifest.id,
	);

	for (const ownerKind of [
		"level",
		"prefab",
		"asset",
		"render-profile",
		"generated-module",
	] as const) {
		assert(
			targets.some((target) => target.ownerKind === ownerKind),
			`Expected ${manifest.id} to have a ${ownerKind} owner target.`,
		);
	}

	assert(
		targets.some(
			(target) =>
				target.generatedOwnerKind === "authoring-save" &&
				target.writableByAuthoringSave,
		),
		`Expected ${manifest.id} to have a writable generated authoring-save target.`,
	);
}

let inspectedSceneSaveCount = 0;

for (const manifest of defaultRuntimeSceneManifests) {
	const workspace = buildLevelEditorWorkspaceModel({
		selectedRuntimeSceneId: manifest.id,
	});
	const object = workspace.objects.find((candidate) =>
		candidate.fields.some((field) => !field.readOnly),
	);
	const field = object?.fields.find((candidate) => !candidate.readOnly);

	if (!object || !field) {
		throw new Error(
			`Expected ${manifest.id} to expose at least one editable inspector field.`,
		);
	}

	const inspectorTransaction = buildAuthoringSaveTransaction({
		workspace,
		edits: [
			{
				stableId: object.stableId,
				path: field.path,
				label: field.label,
				before: field.value,
				after: nextInspectorFieldValue(field.value),
			},
		],
		baseHash: LEVEL_EDITOR_MISSING_FILE_HASH,
	});
	const operation = inspectorTransaction.targets[0]?.operations[0];

	if (!operation) {
		throw new Error(
			`Expected ${manifest.id} inspector save to emit an operation.`,
		);
	}

	assertEqual(
		operation.kind,
		"replace-level-instance",
		`Expected ${manifest.id} inspector field edits to save as level-instance operations.`,
	);
	assertEqual(
		operation.ownerKind,
		"level",
		`Expected ${manifest.id} inspector field edits to target the level owner.`,
	);
	assertEqual(
		operation.ownerTargetId,
		`${manifest.id}:level`,
		`Expected ${manifest.id} inspector field edits to target the selected scene level owner.`,
	);
	inspectedSceneSaveCount += 1;
}

assertEqual(
	inspectedSceneSaveCount,
	defaultRuntimeSceneManifests.length,
	"Expected inspector save coverage for every runtime scene.",
);

const transaction = createTransaction({
	runtimeSceneId: "portal_arena_runtime",
	saveTargetId: "portal_arena_runtime:generated:authoring-save",
	baseHash: LEVEL_EDITOR_MISSING_FILE_HASH,
	ownerTargetId: "portal_arena_runtime:level",
});
const transactionTarget = requireSaveTarget(transaction);
const transactionOperation = requireSaveOperation(transactionTarget);
const writePlan = buildLevelEditorAuthoringSaveWritePlan({
	transaction,
	ownerRegistry: registry,
});
const artifact = writePlan.artifacts[0];

if (!artifact) {
	throw new Error("Expected save write plan to contain one artifact.");
}

assertEqual(
	artifact.targetFile,
	"src/game/editor/authoring/generated/portal_arena_runtime.authoringSave.ts",
	"Expected authoring save to target the scoped generated authoring module.",
);
assertIncludes(
	artifact.serializedPayload,
	"@generated by levelEditorAuthoringSave.v1",
	"Expected generated save module to include the bounded writer marker.",
);
assertEqual(
	artifact.payload.writesRuntimeData,
	false,
	"Expected authoring save module to preserve runtime/editor separation.",
);
assertIncludes(
	artifact.payload.affectedOwnerTargets.map((target) => target.id),
	"portal_arena_runtime:level",
	"Expected generated save module to record affected owner provenance.",
);

const aiApplyQueueEntry = buildLevelEditorAiApplyPlanQueueEntry(
	createAiApplyPlan(),
);
const aiApplySaveOperations = aiApplyQueueEntry.saveOperations ?? [];
assertEqual(
	aiApplySaveOperations.length,
	2,
	"Expected AI apply plans to emit generated save operations for the authoring queue.",
);
assertIncludes(
	aiApplySaveOperations.map((operation) => operation.ownerTargetId),
	"portal_arena_runtime:assets",
	"Expected AI apply generated save operations to affect the asset owner target.",
);
assertEqual(
	aiApplySaveOperations.find(
		(operation) => operation.kind === "replace-level-instance",
	)?.ownerTargetId,
	"portal_arena_runtime:level",
	"Expected AI generated save operations to affect the level owner target.",
);

const aiApplyWritePlan = buildLevelEditorAuthoringSaveWritePlan({
	transaction: {
		schemaVersion: 1,
		transactionId: "save-contract-ai-apply",
		runtimeSceneId: "portal_arena_runtime",
		authoringValidation: {
			status: "valid",
			contract: "LevelEditorAuthoringContract",
			contentHash: "fnv1a32:bbbbbbbb",
		},
		targets: [
			{
				targetId: "portal_arena_runtime:generated:authoring-save",
				baseHash: LEVEL_EDITOR_MISSING_FILE_HASH,
				operations: aiApplySaveOperations,
			},
		],
	},
	ownerRegistry: registry,
});
const aiApplyArtifact = aiApplyWritePlan.artifacts[0];

if (!aiApplyArtifact) {
	throw new Error("Expected AI apply save write plan to contain one artifact.");
}

assertIncludes(
	aiApplyArtifact.payload.affectedOwnerTargets.map((target) => target.id),
	"portal_arena_runtime:level",
	"Expected AI apply generated save module to record affected level owner provenance.",
);
assertIncludes(
	aiApplyArtifact.payload.affectedOwnerTargets.map((target) => target.id),
	"portal_arena_runtime:assets",
	"Expected AI apply generated save module to record affected asset owner provenance.",
);
assertIncludes(
	JSON.stringify(aiApplyArtifact.payload.operations),
	"editor-ai-apply-selection",
	"Expected AI apply generated save payload to preserve its source plan.",
);

assertValidationFailure(
	{
		...transaction,
		targets: [
			{
				...transactionTarget,
				targetId: "portal_arena_runtime:level",
			},
		],
	},
	"is not writable by the level editor save command",
);

assertValidationFailure(
	{
		...transaction,
		targets: [
			{
				...transactionTarget,
				operations: [
					{
						...transactionOperation,
						previewOnly: true,
					} as unknown as LevelEditorAuthoringOperationData,
				],
			},
		],
	},
	"preview-only and cannot be saved",
);

assertValidationFailure(
	{
		...transaction,
		targets: [
			{
				...transactionTarget,
				operations: [
					{
						...transactionOperation,
						ownerTargetId: "portal_arena_runtime:assets",
					},
				],
			},
		],
	},
	"does not match owner target",
);

const tempRoot = await mkdtemp(join(tmpdir(), "level-editor-save-contract-"));

try {
	const dryRun = await saveLevelEditorAuthoringTransaction({
		appRoot: tempRoot,
		transaction,
		dryRun: true,
	});

	assertEqual(dryRun.dryRun, true, "Expected dry run result to be marked.");
	assertEqual(
		dryRun.artifacts[0]?.wroteFile,
		false,
		"Expected dry run to avoid file writes.",
	);

	const saveResult = await saveLevelEditorAuthoringTransaction({
		appRoot: tempRoot,
		transaction,
	});
	const savedArtifact = saveResult.artifacts[0];

	if (!savedArtifact) {
		throw new Error("Expected save result to include an artifact.");
	}

	const savedSource = await readFile(savedArtifact.absolutePath, "utf8");
	assertIncludes(
		savedSource,
		"levelEditorAuthoringSaveModule",
		"Expected save command to write the generated authoring module export.",
	);

	await assertPersistenceFailure(
		saveLevelEditorAuthoringTransaction({
			appRoot: tempRoot,
			transaction,
		}),
		"base hash mismatch",
	);

	const currentHash = hashLevelEditorAuthoringFileContent(savedSource);
	const updateTransaction = createTransaction({
		runtimeSceneId: "portal_arena_runtime",
		saveTargetId: "portal_arena_runtime:generated:authoring-save",
		baseHash: currentHash,
		ownerTargetId: "portal_arena_runtime:level",
		transactionId: "save-contract-update",
		subjectId: "portal-arena:portal:observatory",
	});
	const updateResult = await saveLevelEditorAuthoringTransaction({
		appRoot: tempRoot,
		transaction: updateTransaction,
	});

	assertEqual(
		updateResult.artifacts[0]?.currentHash,
		currentHash,
		"Expected update to verify the current base hash before writing.",
	);

	const nonGeneratedTransaction = createTransaction({
		runtimeSceneId: "prototype_arena_runtime",
		saveTargetId: "prototype_arena_runtime:generated:authoring-save",
		baseHash: LEVEL_EDITOR_MISSING_FILE_HASH,
		ownerTargetId: "prototype_arena_runtime:level",
		transactionId: "save-contract-non-generated",
	});
	const nonGeneratedTransactionTarget = requireSaveTarget(
		nonGeneratedTransaction,
	);
	const nonGeneratedTarget = registry.targets.find(
		(target) =>
			target.id === "prototype_arena_runtime:generated:authoring-save",
	);

	if (!nonGeneratedTarget) {
		throw new Error("Expected prototype generated authoring-save target.");
	}

	const nonGeneratedPath = resolve(tempRoot, nonGeneratedTarget.targetFile);
	const nonGeneratedSource = "export const handwritten = true;\n";
	await mkdir(dirname(nonGeneratedPath), { recursive: true });
	await writeFile(nonGeneratedPath, nonGeneratedSource, "utf8");

	await assertPersistenceFailure(
		saveLevelEditorAuthoringTransaction({
			appRoot: tempRoot,
			transaction: {
				...nonGeneratedTransaction,
				targets: [
					{
						...nonGeneratedTransactionTarget,
						baseHash: hashLevelEditorAuthoringFileContent(nonGeneratedSource),
					},
				],
			},
		}),
		"is not marked as a level editor generated save module",
	);
} finally {
	await rm(tempRoot, { recursive: true, force: true });
}

const routeTempRoot = await mkdtemp(
	join(tmpdir(), "level-editor-save-route-contract-"),
);
const originalNodeEnv = process.env.NODE_ENV;

try {
	process.env.NODE_ENV = "development";

	const initialRouteStatus = await authoringTargetStatus(
		"portal_arena_runtime",
		routeTempRoot,
	);

	assertEqual(
		initialRouteStatus.baseHash,
		LEVEL_EDITOR_MISSING_FILE_HASH,
		"Expected authoring status to report missing generated save modules.",
	);

	const routeDryRunResponse =
		await handleLevelEditorAuthoringPersistenceRequest({
			appRoot: routeTempRoot,
			mode: "dry-run",
			request: jsonRequest({ transaction }),
		});

	assertEqual(routeDryRunResponse.status, 200, "Expected dry-run HTTP 200.");
	const routeDryRun = (await routeDryRunResponse.json()) as ApiResultBody;
	assertEqual(routeDryRun.ok, true, "Expected dry-run API result to succeed.");
	assertEqual(
		routeDryRun.dryRun,
		true,
		"Expected dry-run API result to be marked as a dry run.",
	);
	assertEqual(
		routeDryRun.artifacts?.[0]?.wroteFile,
		false,
		"Expected dry-run API result to avoid writes.",
	);
	assertEqual(
		routeDryRun.artifacts?.[0]?.targetFile,
		"src/game/editor/authoring/generated/portal_arena_runtime.authoringSave.ts",
		"Expected dry-run API result to report the generated authoring-save target.",
	);

	const routeSaveEndpointDryRunResponse =
		await handleLevelEditorAuthoringPersistenceRequest({
			appRoot: routeTempRoot,
			mode: "save",
			request: jsonRequest({
				mode: "dry-run",
				transaction,
			}),
		});

	assertEqual(
		routeSaveEndpointDryRunResponse.status,
		200,
		"Expected save endpoint to honor a dry-run request body mode.",
	);
	const routeSaveEndpointDryRun =
		(await routeSaveEndpointDryRunResponse.json()) as ApiResultBody;
	assertEqual(
		routeSaveEndpointDryRun.dryRun,
		true,
		"Expected save endpoint dry-run request to avoid writes.",
	);

	const routeSaveResponse = await handleLevelEditorAuthoringPersistenceRequest({
		appRoot: routeTempRoot,
		mode: "save",
		request: jsonRequest(transaction),
	});

	assertEqual(routeSaveResponse.status, 201, "Expected save HTTP 201.");
	const routeSave = (await routeSaveResponse.json()) as ApiResultBody;
	assertEqual(routeSave.ok, true, "Expected save API result to succeed.");
	assertEqual(
		routeSave.artifacts?.[0]?.wroteFile,
		true,
		"Expected save API result to write the generated authoring module.",
	);

	const routeConflictResponse =
		await handleLevelEditorAuthoringPersistenceRequest({
			appRoot: routeTempRoot,
			mode: "save",
			request: jsonRequest(transaction),
		});

	assertEqual(
		routeConflictResponse.status,
		409,
		"Expected stale save API request to return HTTP 409.",
	);
	const routeConflict = (await routeConflictResponse.json()) as ApiResultBody;
	assertIncludes(
		routeConflict.error?.message ?? "",
		"base hash mismatch",
		"Expected stale save API response to explain the base hash mismatch.",
	);

	const routeValidationResponse =
		await handleLevelEditorAuthoringPersistenceRequest({
			appRoot: routeTempRoot,
			mode: "dry-run",
			request: jsonRequest({
				...transaction,
				runtimeSceneId: "missing_runtime_scene",
			}),
		});

	assertEqual(
		routeValidationResponse.status,
		400,
		"Expected invalid save transaction to return HTTP 400.",
	);
	const routeValidation =
		(await routeValidationResponse.json()) as ApiResultBody;
	assertIncludes(
		routeValidation.error?.message ?? "",
		"not in the runtime scene catalog",
		"Expected invalid save transaction response to explain registry failure.",
	);

	process.env.NODE_ENV = "production";

	const routeDisabledResponse =
		await handleLevelEditorAuthoringPersistenceRequest({
			appRoot: routeTempRoot,
			mode: "save",
			request: jsonRequest(transaction),
		});

	assertEqual(
		routeDisabledResponse.status,
		403,
		"Expected authoring API save route to be disabled in production.",
	);
	const routeDisabled = (await routeDisabledResponse.json()) as ApiResultBody;
	assertEqual(
		routeDisabled.error?.code,
		"LEVEL_EDITOR_AUTHORING_API_DISABLED",
		"Expected disabled authoring API response to use a stable error code.",
	);
} finally {
	restoreNodeEnv(originalNodeEnv);
	await rm(routeTempRoot, { recursive: true, force: true });
}

console.log(
	`Level editor save contract passed for ${registry.runtimeSceneIds.length} runtime scene owner sets.`,
);

type ApiResultBody = {
	readonly ok?: boolean;
	readonly dryRun?: boolean;
	readonly artifacts?: readonly {
		readonly targetFile?: string;
		readonly wroteFile?: boolean;
	}[];
	readonly error?: {
		readonly code?: string;
		readonly message?: string;
	};
};

function createTransaction(options: {
	readonly runtimeSceneId: string;
	readonly saveTargetId: string;
	readonly baseHash: string;
	readonly ownerTargetId: string;
	readonly transactionId?: string;
	readonly subjectId?: string;
}): LevelEditorAuthoringSaveTransactionData {
	return {
		schemaVersion: 1,
		transactionId: options.transactionId ?? "save-contract-insert",
		runtimeSceneId: options.runtimeSceneId,
		authoringValidation: {
			status: "valid",
			contract: "LevelEditorAuthoringContract",
			contentHash: "fnv1a32:aaaaaaaa",
		},
		targets: [
			{
				targetId: options.saveTargetId,
				baseHash: options.baseHash,
				operations: [
					{
						kind: "replace-level-instance",
						ownerKind: "level",
						ownerTargetId: options.ownerTargetId,
						subjectId: options.subjectId ?? "player",
						payload: {
							components: {
								Transform: {
									position: [0, 1.5, 0],
								},
							},
						},
					},
				],
			},
		],
	};
}

function assertValidationFailure(
	transaction: LevelEditorAuthoringSaveTransactionData,
	expectedMessage: string,
): void {
	try {
		buildLevelEditorAuthoringSaveWritePlan({
			transaction,
			ownerRegistry: registry,
		});
	} catch (error) {
		assertIncludes(
			String(error instanceof Error ? error.message : error),
			expectedMessage,
			`Expected validation failure to mention "${expectedMessage}".`,
		);
		return;
	}

	throw new Error(`Expected validation failure for ${expectedMessage}.`);
}

async function assertPersistenceFailure(
	promise: Promise<unknown>,
	expectedMessage: string,
): Promise<void> {
	try {
		await promise;
	} catch (error) {
		assertIncludes(
			String(error instanceof Error ? error.message : error),
			expectedMessage,
			`Expected persistence failure to mention "${expectedMessage}".`,
		);
		return;
	}

	throw new Error(`Expected persistence failure for ${expectedMessage}.`);
}

function requireSaveTarget(
	transaction: LevelEditorAuthoringSaveTransactionData,
): LevelEditorAuthoringSaveTargetData {
	const target = transaction.targets[0];

	if (!target) {
		throw new Error("Expected test transaction to include a save target.");
	}

	return target;
}

function requireSaveOperation(
	target: LevelEditorAuthoringSaveTargetData,
): LevelEditorAuthoringOperationData {
	const operation = target.operations[0];

	if (!operation) {
		throw new Error("Expected test save target to include an operation.");
	}

	return operation;
}

function nextInspectorFieldValue(value: string | number | boolean) {
	if (typeof value === "number") {
		return value + 1;
	}

	if (typeof value === "boolean") {
		return !value;
	}

	return `${value}-edited`;
}

function assert(value: unknown, message: string): asserts value {
	if (!value) {
		throw new Error(message);
	}
}

function assertEqual<TValue>(
	actual: TValue,
	expected: TValue,
	message: string,
): void {
	if (actual !== expected) {
		throw new Error(`${message} Expected ${expected}, received ${actual}.`);
	}
}

function assertIncludes(
	values: readonly string[] | string,
	expected: string,
	message: string,
): void {
	if (!values.includes(expected)) {
		throw new Error(`${message} Missing ${expected}.`);
	}
}

function jsonRequest(body: unknown): Request {
	return new Request("http://localhost/api/editor/authoring/save.json", {
		body: JSON.stringify(body),
		headers: {
			"content-type": "application/json",
		},
		method: "POST",
	});
}

function restoreNodeEnv(value: string | undefined): void {
	if (value === undefined) {
		process.env.NODE_ENV = undefined;
		return;
	}

	process.env.NODE_ENV = value;
}

function createAiApplyPlan(): EditorAiApplyToSelectionPlan {
	return {
		schemaVersion: 1,
		runtimeSceneId: "portal_arena_runtime",
		generatedAssetId: "generated_asset_portal_crate",
		operation: "replace-selection-renderable",
		previewOnly: false,
		mutatesRuntimeDirectly: false,
		ownerManifestStatus: "requires-generated-manifest-record",
		editOperations: [
			{
				type: "patch-level-instance-renderable",
				runtimeSceneId: "portal_arena_runtime",
				targetStableId: "portal-arena:portal:observatory",
				generatedAssetId: "generated_asset_portal_crate",
				preserveStableId: true,
				componentPatch: {
					Renderable: {
						meshAssetId: "mesh_ai_portal_crate",
					},
				},
				ownerWritePlanStatus: "requires-save",
			},
		],
		fitReport: {
			status: "fit-to-selection",
			sourceStableId: null,
			targetStableIds: ["portal-arena:portal:observatory"],
			transformPolicy: "fit-to-source-bounds",
		},
	};
}
