import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import {
	LEVEL_EDITOR_AUTHORING_SAVE_GENERATOR,
	type LevelEditorAuthoringSaveTransactionData,
	type LevelEditorAuthoringSaveWriteArtifact,
	buildLevelEditorAuthoringSaveWritePlan,
	hashLevelEditorAuthoringFileContent,
} from "./saveTransaction.js";

export type LevelEditorAuthoringPersistenceOptions = {
	readonly appRoot: string | URL;
	readonly transaction: LevelEditorAuthoringSaveTransactionData;
	readonly dryRun?: boolean;
};

export type LevelEditorAuthoringPersistenceArtifactResult = {
	readonly targetId: string;
	readonly targetFile: string;
	readonly absolutePath: string;
	readonly baseHash: string;
	readonly currentHash: string;
	readonly contentHash: string;
	readonly wroteFile: boolean;
};

export type LevelEditorAuthoringPersistenceResult = {
	readonly ok: true;
	readonly dryRun: boolean;
	readonly writePlanContentHash: string;
	readonly artifacts: readonly LevelEditorAuthoringPersistenceArtifactResult[];
};

type PreparedArtifact = {
	readonly artifact: LevelEditorAuthoringSaveWriteArtifact;
	readonly absolutePath: string;
	readonly currentSource: string | undefined;
	readonly currentHash: string;
};

export async function saveLevelEditorAuthoringTransaction(
	options: LevelEditorAuthoringPersistenceOptions,
): Promise<LevelEditorAuthoringPersistenceResult> {
	const appRoot = normalizeAppRoot(options.appRoot);
	const writePlan = buildLevelEditorAuthoringSaveWritePlan({
		transaction: options.transaction,
	});
	const preparedArtifacts = await Promise.all(
		writePlan.artifacts.map((artifact) =>
			prepareArtifact({
				appRoot,
				artifact,
			}),
		),
	);
	const safetyErrors = validatePreparedArtifacts(preparedArtifacts);

	if (safetyErrors.length > 0) {
		throw new Error(
			`Refusing level editor authoring save:\n${safetyErrors.join("\n")}`,
		);
	}

	if (options.dryRun !== true) {
		for (const prepared of preparedArtifacts) {
			await mkdir(dirname(prepared.absolutePath), { recursive: true });
			await writeFile(
				prepared.absolutePath,
				prepared.artifact.serializedPayload,
				"utf8",
			);
		}
	}

	return {
		ok: true,
		dryRun: options.dryRun === true,
		writePlanContentHash: writePlan.contentHash,
		artifacts: preparedArtifacts.map((prepared) => ({
			targetId: prepared.artifact.targetId,
			targetFile: prepared.artifact.targetFile,
			absolutePath: prepared.absolutePath,
			baseHash: prepared.artifact.baseHash,
			currentHash: prepared.currentHash,
			contentHash: prepared.artifact.contentHash,
			wroteFile: options.dryRun !== true,
		})),
	};
}

async function prepareArtifact(options: {
	readonly appRoot: string;
	readonly artifact: LevelEditorAuthoringSaveWriteArtifact;
}): Promise<PreparedArtifact> {
	const absolutePath = resolveTargetPath({
		appRoot: options.appRoot,
		targetFile: options.artifact.targetFile,
	});
	const currentSource = await readOptionalFile(absolutePath);
	const currentHash = hashLevelEditorAuthoringFileContent(currentSource);

	return {
		artifact: options.artifact,
		absolutePath,
		currentSource,
		currentHash,
	};
}

function validatePreparedArtifacts(
	preparedArtifacts: readonly PreparedArtifact[],
): readonly string[] {
	const errors: string[] = [];

	for (const prepared of preparedArtifacts) {
		if (prepared.currentHash !== prepared.artifact.baseHash) {
			errors.push(
				`target "${prepared.artifact.targetFile}" base hash mismatch: expected "${prepared.artifact.baseHash}", found "${prepared.currentHash}".`,
			);
		}

		if (
			prepared.currentSource !== undefined &&
			!prepared.currentSource.includes(
				`@generated by ${LEVEL_EDITOR_AUTHORING_SAVE_GENERATOR}`,
			)
		) {
			errors.push(
				`target "${prepared.artifact.targetFile}" exists but is not marked as a level editor generated save module.`,
			);
		}
	}

	return errors;
}

function normalizeAppRoot(appRoot: string | URL): string {
	if (appRoot instanceof URL) {
		return resolve(fileURLToPath(appRoot));
	}

	return resolve(appRoot);
}

function resolveTargetPath(options: {
	readonly appRoot: string;
	readonly targetFile: string;
}): string {
	if (isAbsolute(options.targetFile)) {
		throw new Error(
			`Refusing absolute level editor authoring target "${options.targetFile}".`,
		);
	}

	const absolutePath = resolve(options.appRoot, options.targetFile);
	const relativePath = relative(options.appRoot, absolutePath);

	if (
		relativePath === "" ||
		relativePath.startsWith("..") ||
		isAbsolute(relativePath) ||
		relativePath.split(sep).includes("..")
	) {
		throw new Error(
			`Refusing level editor authoring target outside app root: "${options.targetFile}".`,
		);
	}

	return absolutePath;
}

async function readOptionalFile(path: string): Promise<string | undefined> {
	try {
		return await readFile(path, "utf8");
	} catch (error) {
		if (isNodeError(error) && error.code === "ENOENT") {
			return undefined;
		}

		throw error;
	}
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
	return error instanceof Error && "code" in error;
}
