import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { defaultRuntimeSceneManifests } from "../../levels/index.js";
import type { PublishedLevelInstanceTransformOverride } from "../../levels/publishedLevelOverrides.js";
import type { TransformOverride } from "../../prefabs/index.js";
import {
	LEVEL_EDITOR_MISSING_FILE_HASH,
	type LevelEditorAuthoringOperationData,
	type LevelEditorAuthoringSaveTransactionData,
	hashLevelEditorAuthoringFileContent,
	validateLevelEditorAuthoringSaveTransaction,
} from "./saveTransaction.js";
import {
	cloneValue,
	hashStableValue,
	isRecord,
	serializeStableValue,
} from "./stableValue.js";

export const LEVEL_EDITOR_PUBLISHED_TRANSFORMS_GENERATOR =
	"levelEditorPublishedTransforms.v1";
export const PUBLISHED_LEVEL_TRANSFORMS_TARGET_FILE =
	"src/game/generated/publishedLevelTransforms.ts";

export type LevelEditorPublishedTransformPersistenceOptions = {
	readonly appRoot: string | URL;
	readonly transaction: LevelEditorAuthoringSaveTransactionData;
	readonly baseHash: string;
	readonly dryRun?: boolean;
};

export type LevelEditorPublishedTransformPersistenceResult = {
	readonly dryRun: boolean;
	readonly targetFile: typeof PUBLISHED_LEVEL_TRANSFORMS_TARGET_FILE;
	readonly absolutePath: string;
	readonly baseHash: string;
	readonly currentHash: string;
	readonly contentHash: string;
	readonly wroteFile: boolean;
	readonly changeset: LevelEditorPublishChangeset;
	readonly overrides: readonly PublishedLevelInstanceTransformOverride[];
	readonly publishedStableIds: readonly string[];
};

export type LevelEditorPublishChangesetEntry = {
	readonly targetFile: string;
	readonly absolutePath: string;
	readonly priorContent: string | undefined;
	readonly priorHash: string;
	readonly currentContent: string;
	readonly currentHash: string;
	readonly noOp: boolean;
};

export type LevelEditorPublishChangeset = {
	readonly schemaVersion: 1;
	readonly entries: readonly LevelEditorPublishChangesetEntry[];
	readonly contentHash: string;
};

export async function publishLevelEditorTransformTransaction(
	options: LevelEditorPublishedTransformPersistenceOptions,
): Promise<LevelEditorPublishedTransformPersistenceResult> {
	const staged = await stagePublishedLevelTransformChangeset(options);
	const committed =
		options.dryRun === true
			? false
			: await commitLevelEditorPublishChangeset(staged.changeset);

	return {
		dryRun: options.dryRun === true,
		targetFile: PUBLISHED_LEVEL_TRANSFORMS_TARGET_FILE,
		absolutePath: staged.absolutePath,
		baseHash: options.baseHash,
		currentHash: staged.changeset.entries[0]?.priorHash ?? options.baseHash,
		contentHash:
			staged.changeset.entries[0]?.currentHash ??
			LEVEL_EDITOR_MISSING_FILE_HASH,
		wroteFile: committed,
		changeset: staged.changeset,
		overrides: staged.overrides,
		publishedStableIds: staged.publishedStableIds,
	};
}

export async function stagePublishedLevelTransformChangeset(
	options: LevelEditorPublishedTransformPersistenceOptions,
): Promise<{
	readonly absolutePath: string;
	readonly changeset: LevelEditorPublishChangeset;
	readonly overrides: readonly PublishedLevelInstanceTransformOverride[];
	readonly publishedStableIds: readonly string[];
}> {
	const validationErrors = validateLevelEditorAuthoringSaveTransaction({
		transaction: options.transaction,
	});

	if (validationErrors.length > 0) {
		throw new Error(
			`Invalid level editor publish transaction:\n${validationErrors.join("\n")}`,
		);
	}

	const absolutePath = resolveTargetPath(options.appRoot);
	const currentSource = await readOptionalFile(absolutePath);
	const currentHash = hashLevelEditorAuthoringFileContent(currentSource);

	if (currentHash !== options.baseHash) {
		throw new Error(
			`Refusing level editor publish: base hash mismatch for ${PUBLISHED_LEVEL_TRANSFORMS_TARGET_FILE}. Expected ${options.baseHash}, found ${currentHash}.`,
		);
	}

	if (
		currentSource !== undefined &&
		!currentSource.includes(
			`@generated by ${LEVEL_EDITOR_PUBLISHED_TRANSFORMS_GENERATOR}`,
		)
	) {
		throw new Error(
			`Refusing level editor publish: ${PUBLISHED_LEVEL_TRANSFORMS_TARGET_FILE} is not marked as a generated published transform module.`,
		);
	}

	const existingOverrides =
		currentSource === undefined
			? []
			: parsePublishedLevelTransformOverrides(currentSource);
	const nextOverrides = mergePublishedTransformOverrides({
		existingOverrides,
		transaction: options.transaction,
	});
	const serializedSource =
		serializePublishedLevelTransformOverridesSource(nextOverrides);
	const contentHash = hashLevelEditorAuthoringFileContent(serializedSource);
	const entry = {
		targetFile: PUBLISHED_LEVEL_TRANSFORMS_TARGET_FILE,
		absolutePath,
		priorContent: currentSource,
		priorHash: currentHash,
		currentContent: serializedSource,
		currentHash: contentHash,
		noOp: currentSource === serializedSource,
	} satisfies LevelEditorPublishChangesetEntry;
	const changesetBase = {
		schemaVersion: 1 as const,
		entries: [entry],
	};

	return {
		absolutePath,
		changeset: {
			...changesetBase,
			contentHash: hashStableValue(
				changesetBase.entries.map((changesetEntry) => ({
					currentHash: changesetEntry.currentHash,
					noOp: changesetEntry.noOp,
					priorHash: changesetEntry.priorHash,
					targetFile: changesetEntry.targetFile,
				})),
			),
		},
		overrides: nextOverrides,
		publishedStableIds: publishedStableIdsFromTransaction(options.transaction),
	};
}

export async function commitLevelEditorPublishChangeset(
	changeset: LevelEditorPublishChangeset,
): Promise<boolean> {
	const writableEntries = changeset.entries.filter((entry) => !entry.noOp);

	try {
		for (const entry of writableEntries) {
			await mkdir(dirname(entry.absolutePath), { recursive: true });
			await writeFile(entry.absolutePath, entry.currentContent, "utf8");
		}
	} catch (error) {
		await rollbackLevelEditorPublishChangeset(changeset);
		throw error;
	}

	return writableEntries.length > 0;
}

export async function rollbackLevelEditorPublishChangeset(
	changeset: LevelEditorPublishChangeset,
): Promise<void> {
	for (const entry of [...changeset.entries].reverse()) {
		if (entry.priorContent === undefined) {
			await rm(entry.absolutePath, { force: true });
			continue;
		}

		await mkdir(dirname(entry.absolutePath), { recursive: true });
		await writeFile(entry.absolutePath, entry.priorContent, "utf8");
	}
}

export function mergePublishedTransformOverrides(options: {
	readonly existingOverrides: readonly PublishedLevelInstanceTransformOverride[];
	readonly transaction: LevelEditorAuthoringSaveTransactionData;
}): readonly PublishedLevelInstanceTransformOverride[] {
	const nextOverridesByKey = new Map(
		options.existingOverrides.map(
			(override) => [overrideKey(override), cloneValue(override)] as const,
		),
	);

	for (const operation of publishableTransformOperations(options.transaction)) {
		const override = publishedTransformOverrideForOperation(
			options.transaction,
			operation,
		);
		nextOverridesByKey.set(overrideKey(override), override);
	}

	return [...nextOverridesByKey.values()].sort((left, right) =>
		overrideKey(left).localeCompare(overrideKey(right)),
	);
}

export function serializePublishedLevelTransformOverridesSource(
	overrides: readonly PublishedLevelInstanceTransformOverride[],
): string {
	return [
		`// @generated by ${LEVEL_EDITOR_PUBLISHED_TRANSFORMS_GENERATOR}`,
		"// Source: LevelEditorPublishedLevelTransformContract. Do not edit by hand.",
		'import type { PublishedLevelInstanceTransformOverride } from "../levels/publishedLevelOverrides.js";',
		"",
		`export const publishedLevelInstanceTransformOverrides: readonly PublishedLevelInstanceTransformOverride[] = ${serializeStableValue(
			overrides,
		).trimEnd()};`,
		"",
	].join("\n");
}

export function parsePublishedLevelTransformOverrides(
	source: string,
): readonly PublishedLevelInstanceTransformOverride[] {
	const marker =
		"export const publishedLevelInstanceTransformOverrides: readonly PublishedLevelInstanceTransformOverride[] = ";
	const start = source.indexOf(marker);

	if (start === -1) {
		throw new Error(
			"Published transform module is missing the override export.",
		);
	}

	const valueStart = start + marker.length;
	const valueEnd = source.indexOf(";", valueStart);

	if (valueEnd === -1) {
		throw new Error("Published transform module has an unsupported shape.");
	}

	const parsed = JSON.parse(source.slice(valueStart, valueEnd)) as unknown;

	if (!Array.isArray(parsed)) {
		throw new Error("Published transform override export must be an array.");
	}

	return parsed.map(parsePublishedTransformOverride);
}

export function publishedStableIdsFromTransaction(
	transaction: LevelEditorAuthoringSaveTransactionData,
): readonly string[] {
	return [
		...new Set(
			publishableTransformOperations(transaction).map(
				(operation) => operation.subjectId,
			),
		),
	].sort();
}

function publishableTransformOperations(
	transaction: LevelEditorAuthoringSaveTransactionData,
): readonly LevelEditorAuthoringOperationData[] {
	const operations = transaction.targets.flatMap((target) => target.operations);
	const publishable = operations.filter(isPublishableLevelTransformOperation);
	const unsupportedLevelOperations = operations.filter(
		(operation) =>
			operation.ownerKind === "level" &&
			!isPublishableLevelTransformOperation(operation),
	);

	if (unsupportedLevelOperations.length > 0) {
		throw new Error(
			`Level editor publish currently supports only level-owned set-transform operations. Unsupported operations: ${unsupportedLevelOperations
				.map((operation) => `${operation.kind}:${operation.subjectId}`)
				.join(", ")}`,
		);
	}

	if (publishable.length === 0) {
		throw new Error(
			"Level editor publish transaction does not contain any publishable level transform operations.",
		);
	}

	return publishable;
}

function isPublishableLevelTransformOperation(
	operation: LevelEditorAuthoringOperationData,
): boolean {
	const payloadOperation = payloadAuthoringOperation(operation);

	return (
		operation.kind === "replace-level-instance" &&
		operation.ownerKind === "level" &&
		payloadOperation?.kind === "set-transform"
	);
}

function publishedTransformOverrideForOperation(
	transaction: LevelEditorAuthoringSaveTransactionData,
	operation: LevelEditorAuthoringOperationData,
): PublishedLevelInstanceTransformOverride {
	const manifest = defaultRuntimeSceneManifests.find(
		(candidate) => candidate.id === transaction.runtimeSceneId,
	);

	if (!manifest) {
		throw new Error(
			`Runtime scene "${transaction.runtimeSceneId}" is not in the runtime scene catalog.`,
		);
	}

	const instance = manifest.level.instances.find(
		(candidate) => candidate.stableId === operation.subjectId,
	);

	if (!instance) {
		throw new Error(
			`Runtime scene "${transaction.runtimeSceneId}" does not contain stable ID "${operation.subjectId}".`,
		);
	}

	const payloadOperation = payloadAuthoringOperation(operation);

	if (payloadOperation?.kind !== "set-transform") {
		throw new Error(
			`Operation "${operation.kind}:${operation.subjectId}" does not contain a set-transform payload.`,
		);
	}

	const transform = parseTransformOverride(payloadOperation.transform);
	const overrideBase = {
		schemaVersion: 1 as const,
		runtimeSceneId: transaction.runtimeSceneId,
		levelId: manifest.level.id,
		stableId: operation.subjectId,
		transform,
		sourceTransactionId: transaction.transactionId,
	};

	return {
		...overrideBase,
		contentHash: hashStableValue(overrideBase),
	};
}

function payloadAuthoringOperation(
	operation: LevelEditorAuthoringOperationData,
): Record<string, unknown> | undefined {
	const payload = operation.payload;

	if (!isRecord(payload) || !isRecord(payload.operation)) {
		return undefined;
	}

	return payload.operation;
}

function parseTransformOverride(value: unknown): TransformOverride {
	if (!isRecord(value)) {
		throw new Error("set-transform payload must include a transform object.");
	}

	const transform = {
		...(value.position === undefined
			? {}
			: { position: parseVector3(value.position, "transform.position") }),
		...(value.rotation === undefined
			? {}
			: { rotation: parseQuaternion(value.rotation, "transform.rotation") }),
		...(value.scale === undefined
			? {}
			: { scale: parseVector3(value.scale, "transform.scale") }),
	};

	if (Object.keys(transform).length === 0) {
		throw new Error(
			"set-transform payload must include position, rotation, or scale.",
		);
	}

	return transform;
}

function parsePublishedTransformOverride(
	value: unknown,
): PublishedLevelInstanceTransformOverride {
	if (!isRecord(value)) {
		throw new Error("Published transform override entries must be objects.");
	}

	return {
		schemaVersion: 1,
		runtimeSceneId: parseString(value.runtimeSceneId, "runtimeSceneId"),
		levelId: parseString(value.levelId, "levelId"),
		stableId: parseString(value.stableId, "stableId"),
		transform: parseTransformOverride(value.transform),
		sourceTransactionId: parseString(
			value.sourceTransactionId,
			"sourceTransactionId",
		),
		contentHash: parseString(value.contentHash, "contentHash"),
	};
}

function parseVector3(
	value: unknown,
	path: string,
): readonly [number, number, number] {
	return parseNumberTuple(value, path, 3) as readonly [number, number, number];
}

function parseQuaternion(
	value: unknown,
	path: string,
): readonly [number, number, number, number] {
	return parseNumberTuple(value, path, 4) as readonly [
		number,
		number,
		number,
		number,
	];
}

function parseNumberTuple(
	value: unknown,
	path: string,
	length: number,
): readonly number[] {
	if (
		!Array.isArray(value) ||
		value.length !== length ||
		value.some((item) => typeof item !== "number" || !Number.isFinite(item))
	) {
		throw new Error(`${path} must be a finite ${length}-number tuple.`);
	}

	return [...value];
}

function parseString(value: unknown, path: string): string {
	if (typeof value !== "string" || value.trim().length === 0) {
		throw new Error(`${path} must be a non-empty string.`);
	}

	return value;
}

function overrideKey(override: {
	readonly runtimeSceneId: string;
	readonly levelId: string;
	readonly stableId: string;
}): string {
	return `${override.runtimeSceneId}\u0000${override.levelId}\u0000${override.stableId}`;
}

function resolveTargetPath(appRoot: string | URL): string {
	return resolve(
		typeof appRoot === "string" ? appRoot : appRoot.pathname,
		PUBLISHED_LEVEL_TRANSFORMS_TARGET_FILE,
	);
}

async function readOptionalFile(path: string): Promise<string | undefined> {
	try {
		return await readFile(path, "utf8");
	} catch (error) {
		if (
			typeof error === "object" &&
			error !== null &&
			"code" in error &&
			error.code === "ENOENT"
		) {
			return undefined;
		}

		throw error;
	}
}
